import assert from "node:assert/strict";
import fs from "node:fs";

const admin = fs.readFileSync(new URL("../../admin/index.html", import.meta.url), "utf8");
const ui = fs.readFileSync(new URL("../../js/m4l-academy-calendar.js", import.meta.url), "utf8");
const css = fs.readFileSync(new URL("../../css/m4l-29-academy-calendar.css", import.meta.url), "utf8");
const account = fs.readFileSync(new URL("../../account/index.html", import.meta.url), "utf8");
const accountUi = fs.readFileSync(new URL("../../js/m4l-account.js", import.meta.url), "utf8");

assert.match(admin, /Academic Calendar/);
assert.match(admin, /data-academy-calendar-action="open"/);
assert.match(admin, /m4l-academy-calendar\.js\?v=106\.1/);
assert.match(ui, /<h3>Holidays<\/h3>/);
assert.match(ui, /Islamic Dates/);
assert.match(ui, /data-academy-calendar-action="add-term"/);
assert.match(ui, /data-academy-calendar-action="add-public"/);
assert.match(ui, /delete-public/);
assert.match(ui, /action === "save-terms"/);
assert.match(ui, /save-islamic/);
assert.match(ui, /save-public/);
assert.match(ui, /event\.description !== "First Fast"/);
assert.match(ui, /event\.islamicDate/);
assert.doesNotMatch(ui, /compactField\("Alternate"/);
assert.doesNotMatch(ui, /compactField\("Teaching"/);
assert.match(ui, /data-field="description" type="text" maxlength="120"/);
assert.match(css, /academy-calendar-header-refresh/);
assert.match(css, /background:transparent !important/);
assert.match(ui, /\/api\/admin\/platform\/calendar\/get/);
assert.match(ui, /\/api\/admin\/platform\/calendar\/batch-save/);
const islamicRowSource = ui.slice(ui.indexOf("function islamicRow"), ui.indexOf("function publicHolidayPanel"));
assert.doesNotMatch(islamicRowSource, /Status|activeSelect|saveIconButton|saveButton/, "Islamic Date rows must contain only informational identity + editable Gregorian date");
assert.match(ui, /saveButton\("Save Islamic Dates", "save-islamic"/);
assert.match(ui, /saveButton\("Save Holidays", "save-public"/);
assert.match(ui, /saveButton\("Save Terms", "save-terms"/);
assert.match(ui, /app-icon app-icon-small save-mode-icon/);
assert.match(css, /academy-calendar-toolbar[\s\S]*flex-wrap:nowrap/);
assert.match(css, /academy-calendar-today-button[^}]*width:auto !important[^}]*min-width:112px/);
assert.match(css, /academy-calendar-year-field[^}]*margin-left:auto/);
assert.match(css, /academy-calendar-public-row \{[\s\S]*grid-template-columns:minmax\(0,1fr\) minmax\(112px,\.78fr\) 34px/);
assert.doesNotMatch(css, /academy-calendar-public-row > input:first-child \{ grid-column:1 \/ -1/);
assert.doesNotMatch(css, /min-width:\s*760px/);
assert.match(css, /--app-icon-url:url\('\/icons\/refresh\.svg'\)/);
assert.match(css, /academy-calendar-reference-grid/);
assert.match(css, /grid-template-columns:minmax\(0,1fr\) minmax\(0,1fr\)/);
assert.match(ui, /academy-calendar-terms/);
assert.match(account, /academy-week-context/);
assert.match(accountUi, /academy-calendar-day-badges/);
assert.match(accountUi, /event\.islamicDate/);
assert.match(accountUi, /RELIGIOUS_PERIOD/);

console.log("V102.12.8 Academic Calendar compact-toolbar, one-row mobile Holidays and section-save UI tests passed.");
