import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

const read = relativePath => readFileSync(new URL(`../../${relativePath}`, import.meta.url), "utf8");
const html = read("admin/index.html");
const script = read("js/m4l-global-curriculum.js");
const academics = read("js/m4l-admin-academics.js");
const css = read("css/m4l-24-global-curriculum.css");
const styles = read("styles.css");

assert.match(html, /id="open-global-curriculum-btn"/);
assert.match(html, /data-global-curriculum-admin/);
assert.match(html, /id="global-curriculum-screen"/);
assert.match(html, /data-gcm-tab="subjects"/);
assert.doesNotMatch(html, /data-gcm-tab="modules"/);
assert.match(html, /data-gcm-tab="tasks"/);
assert.match(html, /data-gcm-tab="resources"/);
assert.match(html, /data-gcm-course-action="show">Courses<\/button>/);
assert.match(html, /data-gcm-tab="access">Global Access<\/button>/);
assert.match(html, /m4l-global-curriculum\.js\?v=106\.1/);
assert.doesNotMatch(html, />Platform administration</);
assert.doesNotMatch(html, /Changes apply across the platform and are recorded in PlatformAuditLog/);

assert.match(script, /platformrole/);
assert.match(script, /ADMIN and GLOBAL_ADMIN/);
assert.match(script, /\/api\/admin\/platform\/global\/get/);
assert.match(script, /\/api\/admin\/platform\/global\/access\/save/);
assert.match(script, /\/api\/admin\/platform\/global\/subjects\/save-batch/);
assert.match(script, /\/api\/admin\/platform\/global\/resources\/save-batch/);
assert.match(script, /Add\/Modify Global Resources/);
assert.match(script, /toggle-resource-editor/);
assert.match(script, /add-resource-inline/);
assert.match(script, /save-resource-screen/);
assert.match(script, /global-resource-screen-save/);
assert.match(script, /is-dirty/);
assert.match(script, /Change global folder/);
assert.match(script, /Add or Modify Global Subjects/);
assert.match(script, /toggle-subject-modules/);
assert.match(script, /add-module-inline/);
assert.match(script, /global-subject-editor-item/);
assert.match(script, /is-dirty/);
assert.match(script, /subjectAccessMatrix/);
assert.match(script, /data-gcm-access-toggle/);
assert.match(script, /global-access-policy-token/);
assert.match(script, /policy === "FREE" \? "FREE" : "PAID"/);
assert.match(script, /global-access-free-state/);
assert.match(script, /Unique ID/);
assert.match(script, /global-access-unique-column/);
assert.doesNotMatch(script, /One row per central account\. FREE subjects are implicit/);
assert.doesNotMatch(script, /Changing a FREE subject to SUBSCRIPTION reuses/);
assert.match(script, /classList\.remove\("is-active"\)/, "Changing tabs must clear the previous active highlight");
assert.match(script, /M4LGlobalCurriculum = Object\.freeze\(\{[\s\S]*invalidate/);
assert.match(academics, /M4LGlobalCurriculum\.syncAccess/);

assert.match(styles, /m4l-24-global-curriculum\.css\?v=103\.1\.0\.3/);
assert.match(css, /\.global-access-matrix/);
assert.match(css, /\.global-access-policy-token/);
assert.match(css, /\.global-access-free-state/);
assert.match(css, /\.global-access-unique-column/);
assert.match(css, /\.global-subject-editor-item\.is-dirty/);
assert.match(css, /\.global-inline-module-editor/);
assert.match(css, /\.global-subject-screen-save/);
assert.match(css, /\.global-resource-list-entry\.is-dirty/);
assert.match(css, /\.global-resource-inline-editor/);
assert.match(css, /\.global-resource-screen-save\.is-dirty/);

console.log("V103.1.0.3 inline Global Subject/Module/Resource editors and Global Access UI tests passed.");
