import assert from 'node:assert/strict';
import {userProfilesFixture} from '../../scripts/user-profiles-fixtures.mjs';
import {profileService} from '../src/profiles/service.js';
import {timetableCoordinator} from '../src/programs/timetable-coordination.js';
import {programRoleAccounts} from '../src/profiles/program-roles.js';
const f=userProfilesFixture(),service=profileService(f.repository),coordinator=timetableCoordinator(f.journal,async()=>({service,user:f.authorize()}));
const save=input=>coordinator.run('save',{...input,operationId:input.operationId||crypto.randomUUID()},'token');
await save({mode:'matrix-prepare'});
let view=await service.read('get');
const account=()=>view.accounts.find(a=>a.accountId==='PERSON');
const profile=(extra={})=>({mode:'profile',accountId:'PERSON',creating:false,displayName:'Changed together',active:true,baseRevision:account().revision,...extra});
const grant=(scopeId,roles)=>{const scope=view.scopes.find(s=>s.id===scopeId),entry=account().assignments.find(g=>g.scopeId===scopeId);return {mode:'matrix-roles',accountId:'PERSON',scopeType:scope.type,scopeId,roles,baseRevision:entry.revision,scopeRevision:scope.revision};};
const original=structuredClone(f.tables);
await assert.rejects(save({mode:'batch',entries:[profile(),grant('PRG-DEMO',['TEACHER']),grant('FREE',['INVALID'])]}),/valid roles/);
assert.deepEqual(f.tables,original,'Invalid later entry must prevent every write');
const request={mode:'batch',operationId:crypto.randomUUID(),entries:[profile(),grant('PRG-DEMO',['TEACHER','STUDENT']),grant('FREE',['SENIOR'])]};
f.failNext('after');await assert.rejects(save(request),/Injected/);
const replay=await save(request);assert(replay.replayed);assert.equal(replay.results.length,3);
assert.equal(f.tables.UserAccounts[1].DisplayName,'Changed together');
assert.equal(f.tables.AcademyAccessMatrix[1]['PROGRAM:PRG-DEMO'],'STUDENT|TEACHER');
assert.equal(f.tables.AcademyAccessMatrix[1]['SUBJECT:FREE'],'SENIOR');
assert.equal(f.plans.at(-1).changes.filter(c=>c.table==='AcademyAccessMatrix').length,1);
assert.equal(f.tables.AcademyProfileOperations.filter(r=>r.OperationID===request.operationId).length,1);
assert(!JSON.stringify(replay).includes('private'));
view=await service.read('get');const stale=grant('FREE',['ADMIN']);
await save(grant('FREE',['TEACHER']));
await assert.rejects(save({mode:'batch',entries:[profile({displayName:'Must not save'}),stale]}),e=>e.code==='ROW_CHANGED'&&e.entryKey==='matrix-roles:PERSON:SUBJECT:FREE');
assert.equal(f.tables.UserAccounts[1].DisplayName,'Changed together');
let accounts=programRoleAccounts(f.tables,'PRG-DEMO',true);
assert.deepEqual(accounts.find(a=>a.AccountID==='PERSON').Roles,['STUDENT','TEACHER']);
f.tables.AcademyAccessMatrix[1]['PROGRAM:PRG-DEMO']='USER';
f.tables.UserCourseAccess.push({AccountID:'PERSON',CourseID:'PRG-DEMO',Role:'ADMIN',Active:true});
assert.deepEqual(programRoleAccounts(f.tables,'PRG-DEMO',true)[1].Roles,[],'Old elevated role cannot resurrect after removal from matrix');
f.tables.AcademyAccessMatrix[1]['PROGRAM:PRG-DEMO']='TEACHER';
f.tables.AcademyAccessReview.find(r=>r.AccountID==='PERSON'&&r.ScopeKey==='PROGRAM:PRG-DEMO').ReviewStatus='REQUIRED';
assert.deepEqual(programRoleAccounts(f.tables,'PRG-DEMO',true)[1].Roles,[],'Unconfirmed imported roles cannot become teachers');
f.tables.AcademyAccessReview.find(r=>r.AccountID==='PERSON'&&r.ScopeKey==='PROGRAM:PRG-DEMO').ReviewStatus='CONFIRMED';
f.tables.UserAccounts[1].Active=false;assert.equal(programRoleAccounts(f.tables,'PRG-DEMO',true)[1].Active,false);
console.log('Batched profiles: validate before any write, merged row writes, stable retry, conflict identity and confirmed program teacher eligibility passed.');
