import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFile} from 'node:fs/promises';
import {timetableFixture} from '../../scripts/program-timetable-fixtures.mjs';
import {readWeeklyDraft} from '../src/programs/weekly-timetable.js';
import {timetableService} from '../src/programs/timetable-service.js';
import {timetableCoordinator} from '../src/programs/timetable-coordination.js';
const source=await readFile(new URL('../../js/m4l-program-timetable.js',import.meta.url),'utf8'),plannerSource=await readFile(new URL('../../js/m4l-timetable-planner.js',import.meta.url),'utf8'),syncSource=await readFile(new URL('../../js/m4l-timetable-sync.js',import.meta.url),'utf8'),markup=await readFile(new URL('../../programs/timetable.html',import.meta.url),'utf8');
assert.match(markup,/js\/m4l-timetable-planner\.js/);assert.match(markup,/id="tt-planner"/);assert.match(markup,/id="tt-board"/);
assert.doesNotMatch(markup,/id="tt-editor"|id="tt-rules"|id="tt-breaks"/);
assert(markup.indexOf('id="tt-save"')<markup.indexOf('id="tt-board"'));
assert(markup.indexOf('id="tt-publish"')<markup.indexOf('id="tt-board"'));
assert(!/Classes learning together|<th>Pattern|First date|Last date|Publication window|tt-exceptions/.test(markup));
assert(!/id="tt-view"|id="tt-adjust"|id="tt-layout"|All classes/.test(markup));
assert.match(markup,/id="tt-preview-type"/);assert.match(markup,/id="tt-preview-target"/);
assert.equal([...markup.matchAll(/type="date"/g)].length,1);
const ids=new Set([...markup.matchAll(/id="([^"]+)"/g)].map(m=>m[1])),elements=new Map(),storage=new Map(),sharedStorage=new Map(),requests=[];
const f=timetableFixture(),service=timetableService(f.repository,f.program,()=>new Date('2026-09-29T09:00:00Z')),coordinator=timetableCoordinator(f.journal,async()=>({service,user:{accountid:'ADMIN'}}));
f.catalog.classes[0].zoomLink='https://zoom.us/j/111';
const draft=readWeeklyDraft(f.draft).draft;draft.rules[0].teacherId='';draft.rules[0].zoomLink='';
await coordinator.run('save',{id:f.program.id,draft,revision:'',operationId:crypto.randomUUID()},'token');
function element(id){assert(ids.has(id),`Missing ${id}`);if(!elements.has(id))elements.set(id,{hidden:false,disabled:false,value:'',textContent:'',innerHTML:'',events:{},classList:{toggle(){}},setAttribute(){},addEventListener(event,fn){this.events[event]=fn;}});return elements.get(id);}
const blockOptions=[],windowEvents={};
const context={console,URL,Image:class{constructor(){this.complete=false;}},URLSearchParams,structuredClone,crypto,location:{search:`?program=${f.program.id}`,href:`https://example.test/programs/timetable.html?program=${f.program.id}`},document:{getElementById:element,querySelectorAll:()=>[],addEventListener(){},fonts:{ready:Promise.resolve()}},localStorage:{getItem:k=>k==='m4l_account_token'?'token':sharedStorage.get(k)||null,setItem:(k,v)=>sharedStorage.set(k,v)},sessionStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v),removeItem:k=>storage.delete(k)},window:{M4L_CONFIG:{API_BASE:''},M4L_TIMEZONES:{options:z=>`<option>${z}</option>`,defaultZone:'Asia/Riyadh'},addEventListener:(name,fn)=>{windowEvents[name]=fn;}},fetch:async(url,options)=>{
 const action=url.split('/').at(-1),body=JSON.parse(options.body);requests.push({action,body});
 try{const result=['save','publish','recover','prepare'].includes(action)?await coordinator.run(action,body,'token'):await service.read(action,body);return {ok:true,status:200,json:async()=>({success:true,coordinatorAvailable:true,...result})};}
 catch(error){return {ok:false,status:error.status||503,json:async()=>({success:false,error:error.message})};}
}};
const settled=async()=>{for(let i=0;i<6;i++)await new Promise(r=>setTimeout(r,2));};
const click=async id=>{await element(id).onclick();await settled();};
context.window.M4L_TIMETABLE_PRESENTATION ||= {model:()=>({}),html:()=>'<span>Lesson Zoom</span>',canvases:()=>[]};
context.window.M4L_TIMETABLE_BLOCKS={model:(result,options)=>{blockOptions.push(options);return {timetableName:options.teacherId?'Teacher A':'Year 1'};},html:model=>`<svg>${model.timetableName} block timetable</svg>`,canvases:()=>[]};
vm.runInNewContext(syncSource,context);
vm.runInNewContext(plannerSource,context);
let plannerState,notifyDraftChange;
const originalMount=context.window.M4L_ASSISTED_PLANNER.mount;
context.window.M4L_ASSISTED_PLANNER.mount=options=>{plannerState=options.state;notifyDraftChange=options.changed;return originalMount(options);};
vm.runInNewContext(source,context);await settled();
assert.equal(element('tt-save-state').textContent,'Saved draft');
assert.equal(element('tt-publish-options').hidden,true);
assert.match(element('tt-board-tabs').innerHTML,/Class:/);
await click('tt-preview');
assert.match(element('tt-validation').innerHTML,/shared lesson Zoom link/);
assert.equal(element('tt-publish').disabled,true);
plannerState.draft.rules[0].zoomLink='https://zoom.us/j/222?pwd=test';
notifyDraftChange();
assert.equal(element('tt-save-state').textContent,'Unsaved draft changes');
await click('tt-save');
assert.equal(element('tt-save-state').textContent,'Saved draft');
await click('tt-preview');
assert.equal(element('tt-publish-options').hidden,false);
assert.equal(element('tt-effective-from').value,'2026-09-29');
assert.match(element('tt-validation').innerHTML,/Weekly timetable checked/);
assert.match(element('tt-occurrences').innerHTML,/Not assigned/);
assert.match(element('tt-occurrences').innerHTML,/href="https:\/\/zoom.us\/j\/222\?pwd=test"/);
assert.match(element('tt-calendar').innerHTML,/Year 1 block timetable/);
await click('tt-publish');
assert.equal(element('tt-live-state').textContent,'In effect · Version 1');
let request=requests.filter(r=>r.action==='publish').at(-1).body;
assert.equal(request.effectiveFrom,'2026-09-29');
assert.equal(request.draft.rules[0].teacherId,'');
assert(!('effectiveFrom' in request.draft));
plannerState.draft.rules[0].startTime='09:00';notifyDraftChange();
await click('tt-preview');
element('tt-effective-from').oninput({target:{value:'2026-10-05'}});
assert.equal(element('tt-publish').disabled,true);
await click('tt-preview');
f.failNext('after');await click('tt-publish');
assert.equal(element('tt-pending').hidden,false);
const retry=requests.filter(r=>r.action==='publish').at(-1).body;
await click('tt-retry');
assert.deepEqual(requests.filter(r=>r.action==='publish').at(-1).body,retry);
assert.equal(element('tt-pending').hidden,true);
assert.match(element('tt-live-state').textContent,/Version 2 from 2026-10-05/);
await click('tt-history');
assert.match(element('tt-history-list').innerHTML,/Scheduled/);
element('tt-history-list').onclick({target:{dataset:{history:f.tables.ProgramTimetablePublications[0].PublicationID}}});
assert.equal(element('tt-publish-options').hidden,true);
assert.equal(element('tt-preview-type').value,'class');
assert.equal(blockOptions.at(-1).classId,f.catalog.classes[0].id);
console.log('Timetable UI: board-only editing, top publication controls, draft saving, effective-date publication, exact retry and history passed.');
