import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFile} from 'node:fs/promises';
import {timetableFixture} from '../../scripts/program-timetable-fixtures.mjs';
import {readWeeklyDraft,normalizeWeeklyDraft,validateWeeklyTimetable} from '../src/programs/weekly-timetable.js';
import {timetableService} from '../src/programs/timetable-service.js';
import {timetableCoordinator} from '../src/programs/timetable-coordination.js';

const f=timetableFixture();
const draft=readWeeklyDraft(f.draft).draft;
const period={id:'PERIOD-1',startTime:'13:00',endTime:'14:00'};
const range=(id,weekday,startTime,endTime,teacherId='TEACHER-1')=>({id:'AVAIL-'+id,teacherId,weekday,startTime,endTime});
draft.planner={periods:[period],availability:[range('MON',1,'13:00','14:00'),range('WED',3,'13:00','14:00')],limits:[{teacherId:'TEACHER-1',maxWeeklyMinutes:120}]};
let result=validateWeeklyTimetable(draft,f.catalog,f.program,'2026-09-29');
assert.equal(result.valid,true);
assert.equal(result.draft.timezone,'Africa/Johannesburg');
assert.equal(result.plannerReview.teachers[0].scheduledMinutes,120);
assert.equal(result.snapshot.planner,undefined,'availability stays out of published timetable snapshots');

let changed=structuredClone(draft);
changed.planner.availability.pop();
result=validateWeeklyTimetable(changed,f.catalog,f.program,'2026-09-29');
assert.equal(result.valid,false);
assert.match(result.issues[0].message,/unavailable/);
changed=structuredClone(draft);changed.planner.availability[0].startTime='13:30';
assert.match(validateWeeklyTimetable(changed,f.catalog,f.program,'2026-09-29').issues[0].message,/unavailable/,'the full lesson must fit inside the available range');
changed=structuredClone(draft);changed.planner.limits[0].maxWeeklyMinutes=60;
assert.match(validateWeeklyTimetable(changed,f.catalog,f.program).issues[0].message,/exceeds/);
changed=structuredClone(draft);changed.planner.periods.push({id:'PERIOD-2',startTime:'13:30',endTime:'14:30'});
assert.match(validateWeeklyTimetable(changed,f.catalog,f.program).issues[0].message,/cannot overlap/);
changed=structuredClone(draft);changed.planner.availability.push(range('OVERLAP',1,'13:30','14:30'));
assert.throws(()=>normalizeWeeklyDraft(changed),/cannot overlap/);
changed=structuredClone(draft);changed.planner.requirements=[{id:'NEED-OLD',weeklyMinutes:180}];
changed.planner.availability.push({teacherId:'TEACHER-2',preferred:[],unavailable:['1:PERIOD-1']});
const migrated=normalizeWeeklyDraft(changed);
assert.equal(migrated.planner.requirements,undefined,'retired weekly targets are removed from draft data');
assert.equal(migrated.planner.availability.length,2,'retired period-status availability is removed');

const fullGrid=structuredClone(draft);
fullGrid.planner.periods=Array.from({length:8},(_,i)=>({id:'PERIOD-'+(i+1),startTime:String(8+i).padStart(2,'0')+':00',endTime:String(9+i).padStart(2,'0')+':00'}));
fullGrid.planner.availability=Array.from({length:15},(_,i)=>Array.from({length:5},(_,day)=>[
  range(i+'-'+day+'-A',day+1,'08:00','12:00','TEACHER-'+i),
  range(i+'-'+day+'-B',day+1,'12:00','16:00','TEACHER-'+i)
])).flat(2);
assert.doesNotThrow(()=>normalizeWeeklyDraft(fullGrid),'15 teachers with two daily ranges fit in one draft');

const coordinator=timetableCoordinator(f.journal,async()=>({service:timetableService(f.repository,f.program),user:{accountid:'ADMIN'}}));
const first=await coordinator.run('save',{id:f.program.id,revision:'',draft,operationId:crypto.randomUUID()},'token');
assert.deepEqual((await timetableService(f.repository,f.program).read('get')).draft.planner,draft.planner);
await assert.rejects(coordinator.run('save',{id:f.program.id,revision:first.revision,draft:f.draft,operationId:crypto.randomUUID()},'token'),/older editor cannot preserve/);
const older={...draft};delete older.planner;
const saved=await coordinator.run('save',{id:f.program.id,revision:first.revision,draft:older,operationId:crypto.randomUUID()},'token');
assert.deepEqual((await timetableService(f.repository,f.program).read('get')).draft.planner,draft.planner,'an older editor cannot erase planner settings');
const blocked=structuredClone(draft);blocked.planner.availability.pop();
await assert.rejects(coordinator.run('publish',{id:f.program.id,revision:saved.revision,draft:blocked,operationId:crypto.randomUUID()},'token'),/Publication blocked/);

const source=await readFile(new URL('../../js/m4l-timetable-planner.js',import.meta.url),'utf8');
const html=await readFile(new URL('../../programs/timetable.html',import.meta.url),'utf8');
assert.doesNotMatch(html,/Weekly teaching requirements|Place requirement/);
assert.doesNotMatch(html,/id="tt-timezone"/);
assert.match(html,/South Africa time/);
const elements=new Map();
function $(id){if(!elements.has(id))elements.set(id,{value:'',innerHTML:'',textContent:'',disabled:false,hidden:false,setAttribute(){},classList:{toggle(){}}});return elements.get(id);}
const state={data:{catalog:f.catalog},draft:{format:draft.format,timezone:draft.timezone,rules:[]}};
const context={window:{},crypto,structuredClone,console,location:{search:'?program=DEMO',href:'https://example.test/programs/timetable.html?program=DEMO'},URL,URLSearchParams};
vm.runInNewContext(source,context);
let changes=0;
const planner=context.window.M4L_ASSISTED_PLANNER.mount({state,$,esc:String,days:['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'],modules:()=>[{id:'MOD-DEMO',name:'Tafseer module'}],changed:()=>{changes++;},locked:()=>false});
$('tt-period-count').value='2';$('tt-period-start').value='08h00';$('tt-period-length').value='60';
$('tt-create-periods').onclick();
assert.equal(state.draft.planner.periods.length,2);
planner.render();
assert.match($('tt-board').innerHTML,/tt-board-grid/,'period setup generates the class board');
$('tt-board-subject').onchange({target:{value:'MOD-DEMO'}});
$('tt-board-teacher').onchange({target:{value:'TEACHER-1'}});
$('tt-board-view').onchange({target:{value:'teacher'}});
assert.match($('tt-board').innerHTML,/Teacher:/,'teacher view uses the same weekly grid');
assert.match($('tt-open-board').href,/board=teacher.*teacher=TEACHER-1/,'the new-tab link keeps the selected teacher');
const [morning,second]=state.draft.planner.periods;
$('tt-availability-day').value='2';$('tt-availability-from').value='08h00';$('tt-availability-to').value='10h00';
$('tt-add-availability').onclick();
assert.equal(state.draft.planner.availability[0].startTime,'08:00');
const event=dataset=>({target:{dataset,closest:()=>({dataset})}});
$('tt-board').onclick(event({boardDay:'1',boardPeriod:morning.id}));
assert.equal(state.draft.rules.length,0);
assert.match($('tt-board-message').textContent,/unavailable/);
$('tt-board').onclick(event({boardDay:'2',boardPeriod:morning.id}));
assert.equal(state.draft.rules.length,1);
assert.equal(state.draft.rules[0].startTime,'08:00');
$('tt-max-hours').onchange({target:{value:'1'}});
$('tt-board').onclick(event({boardDay:'2',boardPeriod:second.id}));
assert.equal(state.draft.rules.length,1);
assert.match($('tt-board-message').textContent,/hour limit/);
$('tt-max-hours').onchange({target:{value:'2'}});
$('tt-board').onclick(event({boardDay:'2',boardPeriod:second.id}));
assert.equal(state.draft.rules.length,2);
const firstRule=state.draft.rules[0];
$('tt-board').onclick(event({boardDay:'2',boardPeriod:morning.id,ruleId:firstRule.id}));
$('tt-move-lesson').onclick();
$('tt-board').onclick(event({boardDay:'3',boardPeriod:morning.id}));
assert.equal(state.draft.rules[0].weekdays[0],2,'move outside availability is rejected');
$('tt-availability-day').value='3';$('tt-availability-from').value='08h00';$('tt-availability-to').value='09h00';
$('tt-add-availability').onclick();
$('tt-board').onclick(event({boardDay:'3',boardPeriod:morning.id}));
assert.equal(state.draft.rules[0].weekdays[0],3);
planner.undo();
assert.equal(state.draft.rules[0].weekdays[0],2);
// The same board can place lessons before a teacher has been assigned.
$('tt-board-view').onchange({target:{value:'class'}});
$('tt-board-teacher').onchange({target:{value:''}});
$('tt-board').onclick(event({boardDay:'4',boardPeriod:morning.id}));
const unassigned=state.draft.rules.find(row=>row.weekdays.includes(4));
assert.equal(unassigned.teacherId,'');
assert.match($('tt-open-board').href,/board=class/);
$('tt-board').onclick(event({boardDay:'4',boardPeriod:morning.id,ruleId:unassigned.id}));
assert.equal($('tt-board-editor').hidden,false);
$('tt-edit-classes').querySelectorAll=()=>[{value:'CLASS-1'}];
$('tt-edit-subject').value='MOD-DEMO';$('tt-edit-teacher').value='TEACHER-2';
$('tt-edit-start').value='08h10';$('tt-edit-end').value='08h50';$('tt-edit-zoom').value='';
$('tt-save-lesson').onclick();
assert.equal(state.draft.rules.find(row=>row.id===unassigned.id).teacherId,'TEACHER-2');
assert.equal(state.draft.rules.find(row=>row.id===unassigned.id).startTime,'08:10');
$('tt-board').onclick(event({boardDay:'4',boardPeriod:morning.id,ruleId:unassigned.id}));
$('tt-delete-lesson').onclick();
assert.equal(state.draft.rules.some(row=>row.id===unassigned.id),false);
planner.undo();
assert.equal(state.draft.rules.some(row=>row.id===unassigned.id),true);
// Editing one occurrence of a recurring lesson leaves its other weekday intact.
const recurring=state.draft.rules.find(row=>row.id===firstRule.id);recurring.weekdays=[2,3];$('tt-max-hours').onchange({target:{value:'4'}});planner.render();
$('tt-board').onclick(event({boardDay:'2',boardPeriod:morning.id,ruleId:recurring.id}));
$('tt-edit-classes').querySelectorAll=()=>[{value:'CLASS-1'}];
$('tt-edit-subject').value='MOD-DEMO';$('tt-edit-teacher').value='TEACHER-1';
$('tt-edit-start').value='08h10';$('tt-edit-end').value='08h50';$('tt-edit-zoom').value='';
$('tt-save-lesson').onclick();
assert.deepEqual(recurring.weekdays,[3]);
assert(state.draft.rules.some(row=>row.weekdays.length===1&&row.weekdays[0]===2&&row.startTime==='08:10'));
assert.match($('tt-board').innerHTML,/Edit · Move · Delete/);
$('tt-board').onclick(event({boardDay:'3',boardPeriod:morning.id,ruleId:recurring.id}));
$('tt-delete-lesson').onclick();
assert.equal(state.draft.rules.some(row=>row.id===recurring.id),false);
assert(state.draft.rules.some(row=>row.weekdays[0]===2&&row.startTime==='08:10'),'deleting Wednesday retains the edited Tuesday lesson');
assert(changes>=8);
const syncSource=await readFile(new URL('../../js/m4l-timetable-sync.js',import.meta.url),'utf8');
const syncContext={window:{},structuredClone};vm.runInNewContext(syncSource,syncContext);
const merge=syncContext.window.M4L_TIMETABLE_SYNC.merge;
const base={format:'weekly',rules:[{id:'A',teacherId:'T1',startTime:'08:00'}],planner:{periods:[]}};
const ours=structuredClone(base),theirs=structuredClone(base);
ours.rules.push({id:'B',teacherId:'',startTime:'09:00'});
theirs.rules[0].teacherId='T2';
const combined=merge(base,ours,theirs);
assert.equal(combined.rules.length,2,'different boards can add and edit lessons together');
assert.equal(combined.rules[0].teacherId,'T2');
const competing=structuredClone(base);competing.rules[0].teacherId='T3';
assert.throws(()=>merge(base,theirs,competing),/same timetable item/,'same-field edits from two tabs cannot overwrite one another');
assert.throws(()=>merge(base,{...base,rules:[]},theirs),/same timetable item/,'deletion cannot silently discard another tab’s edit');
console.log('Assisted planner: optional teachers, direct board edit/delete/move, recurring weekdays and undo passed.');
