import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFile} from 'node:fs/promises';
import {timetableFixture} from '../../scripts/program-timetable-fixtures.mjs';
import {readWeeklyDraft,normalizeWeeklyDraft,validateWeeklyTimetable} from '../src/programs/weekly-timetable.js';
import {timetableService} from '../src/programs/timetable-service.js';
import {timetableCoordinator} from '../src/programs/timetable-coordination.js';

const f=timetableFixture();
const draft=readWeeklyDraft(f.draft).draft;
const period={id:'PERIOD-1',startTime:'13:00',endTime:'14:00'};
const range=(id,weekday,startTime,endTime,teacherId='TEACHER-1')=>({id:'AVAIL-'+id,teacherId,weekday,startTime,endTime});
draft.planner={periods:[period],availability:[range('MON',1,'13:00','14:00'),range('WED',3,'13:00','14:00')],limits:[{teacherId:'TEACHER-1',maxWeeklyMinutes:120}]};
let result=validateWeeklyTimetable(draft,f.catalog,f.program,'2026-09-29');
assert.equal(result.valid,true);
assert.equal(result.draft.timezone,'Africa/Johannesburg');
assert.equal(result.plannerReview.teachers[0].scheduledMinutes,120);
assert.equal(result.snapshot.planner,undefined,'availability stays out of published timetable snapshots');

let changed=structuredClone(draft);
changed.planner.availability.pop();
result=validateWeeklyTimetable(changed,f.catalog,f.program,'2026-09-29');
assert.equal(result.valid,false);
assert.match(result.issues[0].message,/unavailable/);
changed=structuredClone(draft);changed.planner.availability[0].startTime='13:30';
assert.match(validateWeeklyTimetable(changed,f.catalog,f.program,'2026-09-29').issues[0].message,/unavailable/,'the full lesson must fit inside the available range');
changed=structuredClone(draft);changed.planner.limits[0].maxWeeklyMinutes=60;
assert.match(validateWeeklyTimetable(changed,f.catalog,f.program).issues[0].message,/exceeds/);
changed=structuredClone(draft);changed.planner.periods.push({id:'PERIOD-2',startTime:'13:30',endTime:'14:30'});
assert.match(validateWeeklyTimetable(changed,f.catalog,f.program).issues[0].message,/cannot overlap/);
changed=structuredClone(draft);changed.planner.availability.push(range('OVERLAP',1,'13:30','14:30'));
assert.throws(()=>normalizeWeeklyDraft(changed),/cannot overlap/);
changed=structuredClone(draft);changed.planner.requirements=[{id:'NEED-OLD',weeklyMinutes:180}];
changed.planner.availability.push({teacherId:'TEACHER-2',preferred:[],unavailable:['1:PERIOD-1']});
const migrated=normalizeWeeklyDraft(changed);
assert.equal(migrated.planner.requirements,undefined,'retired weekly targets are removed from draft data');
assert.equal(migrated.planner.availability.length,2,'retired period-status availability is removed');

const fullGrid=structuredClone(draft);
fullGrid.planner.periods=Array.from({length:8},(_,i)=>({id:'PERIOD-'+(i+1),startTime:String(8+i).padStart(2,'0')+':00',endTime:String(9+i).padStart(2,'0')+':00'}));
fullGrid.planner.availability=Array.from({length:15},(_,i)=>Array.from({length:5},(_,day)=>[
  range(i+'-'+day+'-A',day+1,'08:00','12:00','TEACHER-'+i),
  range(i+'-'+day+'-B',day+1,'12:00','16:00','TEACHER-'+i)
])).flat(2);
assert.doesNotThrow(()=>normalizeWeeklyDraft(fullGrid),'15 teachers with two daily ranges fit in one draft');

const coordinator=timetableCoordinator(f.journal,async()=>({service:timetableService(f.repository,f.program),user:{accountid:'ADMIN'}}));
const first=await coordinator.run('save',{id:f.program.id,revision:'',draft,operationId:crypto.randomUUID()},'token');
assert.deepEqual((await timetableService(f.repository,f.program).read('get')).draft.planner,draft.planner);
await assert.rejects(coordinator.run('save',{id:f.program.id,revision:first.revision,draft:f.draft,operationId:crypto.randomUUID()},'token'),/older editor cannot preserve/);
const older={...draft};delete older.planner;
const saved=await coordinator.run('save',{id:f.program.id,revision:first.revision,draft:older,operationId:crypto.randomUUID()},'token');
assert.deepEqual((await timetableService(f.repository,f.program).read('get')).draft.planner,draft.planner,'an older editor cannot erase planner settings');
const blocked=structuredClone(draft);blocked.planner.availability.pop();
await assert.rejects(coordinator.run('publish',{id:f.program.id,revision:saved.revision,draft:blocked,operationId:crypto.randomUUID()},'token'),/Publication blocked/);

const source=await readFile(new URL('../../js/m4l-timetable-planner.js',import.meta.url),'utf8');
const html=await readFile(new URL('../../programs/timetable.html',import.meta.url),'utf8');
assert.doesNotMatch(html,/Weekly teaching requirements|Place requirement/);
assert.doesNotMatch(html,/id="tt-timezone"/);
assert.doesNotMatch(html,/id="tt-move-lesson"/);
assert.doesNotMatch(html,/id="tt-open-board"/,'board tabs stay inside the timetable screen');
assert.match(html,/id="tt-add-board-tab"/);
assert.match(html,/South Africa time/);
assert.match(html,/id="tt-availability-days"/);
assert.match(html,/id="tt-availability-tabs"/);
assert.match(html,/id="tt-availability-dialog"/);
const quickDialogStart=html.indexOf('<dialog id="tt-quick-lesson-dialog"');
assert(quickDialogStart<html.indexOf('<div id="tt-board-editor"')&&html.indexOf('<div id="tt-board-editor"')<html.indexOf('</dialog>',quickDialogStart),'More details stays inside the quick edit popup');
const elements=new Map();
function $(id){if(!elements.has(id))elements.set(id,{value:'',innerHTML:'',textContent:'',disabled:false,hidden:false,open:false,setAttribute(){},showModal(){this.open=true;},close(){this.open=false;},classList:{toggle(){}}});return elements.get(id);}
const state={data:{catalog:f.catalog},draft:{format:draft.format,timezone:draft.timezone,rules:[]}};
const context={window:{confirm:()=>true},crypto,structuredClone,console,location:{search:'?program=DEMO',href:'https://example.test/programs/timetable.html?program=DEMO'},URL,URLSearchParams};
vm.runInNewContext(source,context);
let changes=0;
const planner=context.window.M4L_ASSISTED_PLANNER.mount({state,$,esc:String,days:['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'],modules:()=>[{id:'MOD-DEMO',name:'Tafseer module'},{id:'subject:PS-TAFSEER',name:'Tafseer subject'}],changed:()=>{changes++;},locked:()=>false});
$('tt-period-count').value='2';$('tt-period-start').value='08h00';$('tt-period-length').value='60';
$('tt-create-periods').onclick();
assert.equal(state.draft.planner.periods.length,2);
planner.render();
assert.match($('tt-board').innerHTML,/tt-board-grid/,'period setup generates the class board');
assert.equal($('tt-period-setup').hidden,true,'setup controls give way to period editing on the board');
assert.match($('tt-board').innerHTML,/data-time="startTime"/,'period times are editable in the board row heading');
$('tt-board-subject').onchange({target:{value:'MOD-DEMO'}});
$('tt-board-teacher').onchange({target:{value:'TEACHER-1'}});
$('tt-board-view').onchange({target:{value:'teacher'}});
assert.match($('tt-board').innerHTML,/Teacher:/,'teacher view uses the same weekly grid');
assert.match($('tt-board-tabs').innerHTML,/Teacher:/);
$('tt-add-board-tab').onclick();
assert.equal($('tt-board-view').value,'class','a new in-page tab can show a class board');
$('tt-board-class').onchange({target:{value:'CLASS-2'}});
$('tt-board-subject').onchange({target:{value:'subject:PS-TAFSEER'}});
const tabIds=[...$('tt-board-tabs').innerHTML.matchAll(/data-board-tab="([^"]+)"/g)].map(match=>match[1]);
assert.equal(tabIds.length,2);
const boardTabEvent=(id,close=false)=>({target:{closest:selector=>selector===(close?'[data-close-board-tab]':'[data-board-tab]')?{dataset:close?{closeBoardTab:id}:{boardTab:id}}:null}});
$('tt-board-teacher').onchange({target:{value:'TEACHER-1'}});
const sharedPeriod=state.draft.planner.periods[0];
$('tt-board').onclick({target:{dataset:{boardDay:'0',boardPeriod:sharedPeriod.id},closest:selector=>selector==='[data-board-period]'?{dataset:{boardDay:'0',boardPeriod:sharedPeriod.id}}:null}});
const sharedRule=state.draft.rules.at(-1);
assert(sharedRule.classIds.includes('CLASS-2'));
$('tt-board-tabs').onclick(boardTabEvent(tabIds[0]));
assert.equal($('tt-board-view').value,'teacher');assert.equal($('tt-board-teacher').value,'TEACHER-1');
assert.equal($('tt-board-subject').value,'MOD-DEMO','the original tab keeps its subject choice');
assert.match($('tt-board').innerHTML,new RegExp('data-rule-id="'+sharedRule.id+'"'),'a lesson from the class tab appears in the teacher tab');
planner.undo();
$('tt-board-tabs').onclick(boardTabEvent(tabIds[1]));
assert.equal($('tt-board-class').value,'CLASS-2','each tab remembers its board');
assert.equal($('tt-board-subject').value,'subject:PS-TAFSEER');
assert.doesNotMatch($('tt-board').innerHTML,new RegExp('data-rule-id="'+sharedRule.id+'"'),'undo from one tab updates the other');
$('tt-board-tabs').onclick(boardTabEvent(tabIds[1],true));
assert.equal($('tt-board-view').value,'teacher','closing the active tab returns to the remaining board');
const [morning,second]=state.draft.planner.periods;
const chooseAvailabilityDays=chosen=>{
  for(const day of [1,2,3,4,5,6,0])$('tt-availability-days').onchange({target:{type:'checkbox',value:String(day),checked:chosen.includes(day)}});
};
chooseAvailabilityDays([2]);$('tt-availability-from').value='08h00';$('tt-availability-to').value='10h00';
$('tt-add-availability').onclick();
assert.equal(state.draft.planner.availability[0].startTime,'08:00');
assert.doesNotMatch($('tt-board').innerHTML,/unavailable during this whole period/,'availability does not fill empty board cells with warnings');
const event=dataset=>({target:{dataset,closest:selector=>{
  if(selector==='[data-delete-card]')return dataset.deleteCard!==undefined?{dataset}:null;
  if(selector==='[data-remove-period]')return dataset.removePeriod!==undefined?{dataset}:null;
  if(selector==='[data-board-period]')return dataset.boardPeriod!==undefined?{dataset}:null;
  if(selector==='[data-break-id]')return dataset.breakId!==undefined?{dataset}:null;
  if(selector==='[data-break-gap-start]')return dataset.breakGapStart!==undefined?{dataset}:null;
  return null;
}}});
const dragLesson=(id,fromDay,toDay,periodId)=>{
  let data='';const transfer={setData:(type,value)=>{data=value;},getData:()=>data};
  $('tt-board').ondragstart({target:{closest:selector=>selector==='[data-rule-id]'?{dataset:{ruleId:id,boardDay:String(fromDay)}}:null},dataTransfer:transfer});
  const target={dataset:{boardDay:String(toDay),boardPeriod:periodId,openLesson:'true'}};
  $('tt-board').ondrop({target:{closest:()=>target},dataTransfer:transfer,preventDefault(){}});
  return data;
};
// A teacher board fixes the teacher and asks for the class in both quick forms.
assert.equal($('tt-board-view').value,'teacher');
$('tt-board').onclick(event({boardDay:'2',boardPeriod:morning.id,openLesson:'true'}));
assert.match($('tt-board').innerHTML,/data-quick-class/);
assert.doesNotMatch($('tt-board').innerHTML,/data-quick-teacher/);
$('tt-board').onchange({target:{dataset:{quickClass:''},value:'CLASS-2'}});
$('tt-board').onclick(event({boardDay:'2',boardPeriod:morning.id,placeLesson:''}));
const teacherBoardRule=state.draft.rules.at(-1);
assert.deepEqual(Array.from(teacherBoardRule.classIds),['CLASS-2']);
assert.equal(teacherBoardRule.teacherId,'TEACHER-1');
$('tt-board').onclick(event({boardDay:'2',boardPeriod:morning.id,ruleId:teacherBoardRule.id}));
assert.match($('tt-quick-fields').innerHTML,/data-inline-class/);
assert.doesNotMatch($('tt-quick-fields').innerHTML,/data-inline-teacher/);
$('tt-quick-lesson-dialog').onchange({target:{dataset:{inlineClass:''},value:'CLASS-1'}});
$('tt-quick-save').onclick();
assert.deepEqual(Array.from(teacherBoardRule.classIds),['CLASS-1']);
assert.equal(teacherBoardRule.teacherId,'TEACHER-1');
planner.undo();planner.undo();
$('tt-board-class').onchange({target:{value:'CLASS-1'}});
$('tt-board').onclick(event({boardDay:'1',boardPeriod:morning.id,openLesson:'true'}));
assert.doesNotMatch($('tt-board').innerHTML,/unavailable during this whole period/,'opening a lesson form does not warn before placement');
$('tt-board').onclick(event({boardDay:'1',boardPeriod:morning.id,placeLesson:''}));
assert.equal(state.draft.rules.length,0);
assert.match($('tt-board-message').textContent,/unavailable/);
assert.equal(($('tt-board').innerHTML.match(/tt-board-cell-error/g)||[]).length,1,'only the attempted cell shows the availability error');
$('tt-board').onclick(event({cancelQuick:''}));
assert.doesNotMatch($('tt-board').innerHTML,/tt-board-cell-error/,'cancel clears the cell error');
$('tt-board').onclick(event({boardDay:'2',boardPeriod:morning.id}));
assert.equal(state.draft.rules.length,1);
assert.equal(state.draft.rules[0].startTime,'08:00');
$('tt-max-hours').onchange({target:{value:'1'}});
$('tt-board').onclick(event({boardDay:'2',boardPeriod:second.id}));
assert.equal(state.draft.rules.length,1);
assert.match($('tt-board-message').textContent,/hour limit/);
$('tt-max-hours').onchange({target:{value:'2'}});
$('tt-board').onclick(event({boardDay:'2',boardPeriod:second.id}));
assert.equal(state.draft.rules.length,2);
const firstRule=state.draft.rules[0];
$('tt-board').onclick(event({boardDay:'2',boardPeriod:morning.id,ruleId:firstRule.id}));
dragLesson(firstRule.id,2,3,morning.id);
assert.equal(state.draft.rules[0].weekdays[0],2,'move outside availability is rejected');
chooseAvailabilityDays([3]);$('tt-availability-from').value='08h00';$('tt-availability-to').value='09h00';
$('tt-add-availability').onclick();
dragLesson(firstRule.id,2,3,morning.id);
assert.equal(state.draft.rules[0].weekdays[0],3);
planner.undo();
assert.equal(state.draft.rules[0].weekdays[0],2);
// The same board can place lessons before a teacher has been assigned.
$('tt-board-view').onchange({target:{value:'class'}});
$('tt-board-teacher').onchange({target:{value:''}});
$('tt-board').onclick(event({boardDay:'4',boardPeriod:morning.id}));
const unassigned=state.draft.rules.find(row=>row.weekdays.includes(4));
assert.equal(unassigned.teacherId,'');
assert.match($('tt-board-tabs').innerHTML,/Class:/);
$('tt-board').onclick(event({boardDay:'4',boardPeriod:morning.id,ruleId:unassigned.id}));
assert.equal($('tt-quick-lesson-dialog').open,true,'lesson editing opens a modal');
assert.equal($('tt-board-editor').hidden,true,'the detailed editor stays hidden until requested');
$('tt-quick-lesson-dialog').onchange({target:{dataset:{inlineTeacher:''},value:'TEACHER-2'}});
$('tt-quick-more').onclick();
assert.equal($('tt-quick-lesson-dialog').open,true,'More details stays in the centered popup');
assert.equal($('tt-board-editor').hidden,false);
assert.equal($('tt-quick-fields').hidden,true,'the detailed fields replace the quick fields');
assert.equal($('tt-edit-teacher').value,'TEACHER-2','More details keeps choices made in the modal');
$('tt-edit-classes').querySelectorAll=()=>[{value:'CLASS-1'}];
$('tt-edit-subject').value='MOD-DEMO';$('tt-edit-teacher').value='TEACHER-2';
$('tt-edit-start').value='08h10';$('tt-edit-end').value='08h50';$('tt-edit-zoom').value='';
$('tt-save-lesson').onclick();
assert.equal(state.draft.rules.find(row=>row.id===unassigned.id).teacherId,'TEACHER-2');
assert.equal(state.draft.rules.find(row=>row.id===unassigned.id).startTime,'08:10');
$('tt-board').onclick(event({boardDay:'4',boardPeriod:morning.id,ruleId:unassigned.id}));
$('tt-quick-more').onclick();
$('tt-delete-lesson').onclick();
assert.equal(state.draft.rules.some(row=>row.id===unassigned.id),false);
planner.undo();
assert.equal(state.draft.rules.some(row=>row.id===unassigned.id),true);
// Editing one occurrence of a recurring lesson leaves its other weekday intact.
const recurring=state.draft.rules.find(row=>row.id===firstRule.id);recurring.weekdays=[2,3];$('tt-max-hours').onchange({target:{value:'4'}});planner.render();
$('tt-board').onclick(event({boardDay:'2',boardPeriod:morning.id,ruleId:recurring.id}));
$('tt-quick-more').onclick();
$('tt-edit-classes').querySelectorAll=()=>[{value:'CLASS-1'}];
$('tt-edit-subject').value='MOD-DEMO';$('tt-edit-teacher').value='TEACHER-1';
$('tt-edit-start').value='08h10';$('tt-edit-end').value='08h50';$('tt-edit-zoom').value='';
$('tt-save-lesson').onclick();
assert.deepEqual(recurring.weekdays,[3]);
assert(state.draft.rules.some(row=>row.weekdays.length===1&&row.weekdays[0]===2&&row.startTime==='08:10'));
assert.match($('tt-board').innerHTML,/data-edit-card/);
assert.match($('tt-board').innerHTML,/data-delete-card/);
$('tt-board').onclick(event({boardDay:'3',boardPeriod:morning.id,ruleId:recurring.id}));
$('tt-quick-more').onclick();
$('tt-delete-lesson').onclick();
assert.equal(state.draft.rules.some(row=>row.id===recurring.id),false);
assert(state.draft.rules.some(row=>row.weekdays[0]===2&&row.startTime==='08:10'),'deleting Wednesday retains the edited Tuesday lesson');
const timesBefore=state.draft.rules.map(row=>[row.startTime,row.endTime]);
$('tt-board').onchange({target:{dataset:{period:morning.id,time:'startTime'},value:'745'}});
assert.equal(state.draft.planner.periods[0].startTime,'07:45');
assert.match($('tt-board').innerHTML,/value="07h45"/,'745 is displayed as 07h45');
assert.deepEqual(state.draft.rules.map(row=>[row.startTime,row.endTime]),timesBefore,'period edits keep existing lesson times fixed');
$('tt-board').onchange({target:{dataset:{period:morning.id,time:'endTime'},value:'930'}});
assert.equal(state.draft.planner.periods[0].endTime,'09:00','overlapping period changes are rejected');
assert.match($('tt-board-message').textContent,/cannot overlap/);
planner.undo();assert.equal(state.draft.planner.periods[0].startTime,'08:00');
$('tt-add-period').onclick();assert.equal(state.draft.planner.periods.length,3);
const addedPeriod=state.draft.planner.periods[2];
$('tt-board').onclick(event({removePeriod:addedPeriod.id}));assert.equal(state.draft.planner.periods.length,2);
$('tt-board').onclick(event({removePeriod:morning.id}));assert.equal(state.draft.planner.periods.length,2,'occupied periods cannot be removed');
$('tt-mark-break').onclick();$('tt-board-break-label').value='Lunch';
$('tt-board').onclick(event({boardDay:'1',boardPeriod:second.id}));
assert.equal(state.draft.breaks.length,1);
assert.equal(state.draft.breaks[0].label,'Lunch');
planner.undo();assert.equal(Object.hasOwn(state.draft,'breaks'),false,'undo restores a draft that had no breaks');
$('tt-board').onclick(event({boardDay:'1',boardPeriod:second.id}));
$('tt-board').onclick(event({boardDay:'2',boardPeriod:second.id}));
assert.equal(state.draft.breaks.length,1,'breaks cannot overlap lessons');
$('tt-board').onclick(event({boardDay:'3',boardPeriod:second.id}));
assert.deepEqual(Array.from(state.draft.breaks[0].weekdays),[1,3],'matching breaks on other weekdays share a row');
$('tt-board-class').onchange({target:{value:'CLASS-2'}});
assert.match($('tt-board').innerHTML,/data-break-id=/,'breaks appear on every class board');
const originalBreak=state.draft.breaks[0];
$('tt-board').onclick(event({boardDay:'1',boardPeriod:second.id,breakId:originalBreak.id}));
assert.equal($('tt-break-editor').hidden,false);
$('tt-break-label').value='Lunch';$('tt-break-start').value='0910';$('tt-break-end').value='0950';
$('tt-save-break').onclick();
assert.deepEqual(Array.from(originalBreak.weekdays),[3]);
const editedBreak=state.draft.breaks.find(row=>row.weekdays.includes(1));
assert.equal(editedBreak.startTime,'09:10');
$('tt-board').onclick(event({boardDay:'1',boardPeriod:second.id,breakId:editedBreak.id}));
$('tt-move-break').onclick();$('tt-board').onclick(event({boardDay:'5',boardPeriod:second.id}));
assert.deepEqual(Array.from(editedBreak.weekdays),[5]);
$('tt-board').onclick(event({boardDay:'5',boardPeriod:second.id,breakId:editedBreak.id}));
$('tt-delete-break').onclick();
assert.equal(state.draft.breaks.some(row=>row.id===editedBreak.id),false);
planner.undo();assert.equal(state.draft.breaks.some(row=>row.id===editedBreak.id),true);
$('tt-board').onclick(event({boardDay:'0',boardPeriod:morning.id,openLesson:'true'}));
assert.match($('tt-board').innerHTML,/data-quick-subject/,'an empty cell opens subject and teacher dropdowns');
$('tt-board').onchange({target:{dataset:{quickSubject:''},value:'MOD-DEMO'}});
$('tt-board').onchange({target:{dataset:{quickTeacher:''},value:'TEACHER-2'}});
$('tt-board').onclick(event({boardDay:'0',boardPeriod:morning.id,placeLesson:''}));
const inlineRule=state.draft.rules.find(row=>row.weekdays.includes(0));
assert.equal(inlineRule.teacherId,'TEACHER-2');
const editIconTarget={dataset:{editCard:'',boardDay:'0',boardPeriod:morning.id,ruleId:inlineRule.id}};
const boardBeforeEdit=$('tt-board').innerHTML;
$('tt-board').scrollTop=170;$('tt-board').scrollLeft=80;
$('tt-board').onclick({target:{dataset:editIconTarget.dataset,closest:selector=>selector==='[data-board-period]'?editIconTarget:null}});
assert.equal($('tt-quick-lesson-dialog').open,true);
assert.match($('tt-quick-fields').innerHTML,/data-inline-subject/,'the modal has subject and teacher quick edits');
assert.equal($('tt-board').innerHTML,boardBeforeEdit,'opening quick edit does not redraw or resize the board');
assert.equal($('tt-board').scrollTop,170);assert.equal($('tt-board').scrollLeft,80);
$('tt-quick-lesson-dialog').onchange({target:{dataset:{inlineSubject:''},value:'subject:PS-TAFSEER'}});
$('tt-quick-lesson-dialog').onchange({target:{dataset:{inlineTeacher:''},value:''}});
$('tt-edit-classes').querySelectorAll=()=>[{value:'CLASS-2'}];
$('tt-quick-save').onclick();
assert.equal($('tt-quick-lesson-dialog').open,false,'saving closes quick edit');
assert.equal(inlineRule.moduleId,'');assert.equal(inlineRule.programSubjectId,'PS-TAFSEER');assert.equal(inlineRule.teacherId,'');
$('tt-board').onclick({target:{dataset:editIconTarget.dataset,closest:selector=>selector==='[data-board-period]'?editIconTarget:null}});
$('tt-quick-lesson-dialog').onchange({target:{dataset:{inlineTeacher:''},value:'TEACHER-1'}});
$('tt-quick-save').onclick();
assert.equal($('tt-quick-lesson-dialog').open,true,'a rejected edit keeps the modal open');
assert.match($('tt-quick-error').textContent,/unavailable/,'the reason appears inside the modal');
let escapePrevented=false;
$('tt-quick-lesson-dialog').oncancel({preventDefault(){escapePrevented=true;}});
assert.equal(escapePrevented,true);assert.equal($('tt-quick-lesson-dialog').open,false,'Escape closes without saving');
assert.equal(inlineRule.teacherId,'');
const dragged=dragLesson(inlineRule.id,0,5,morning.id);
assert.equal(JSON.parse(dragged).id,inlineRule.id);
assert.deepEqual(Array.from(inlineRule.weekdays),[5],'dragging moves the selected weekday');
planner.undo();assert.deepEqual(Array.from(state.draft.rules.find(row=>row.id===inlineRule.id).weekdays),[0]);
const day0Rule=state.draft.rules.find(row=>row.id===inlineRule.id);
day0Rule.weekdays=[0,6];planner.render();
$('tt-board').onclick(event({boardDay:'0',boardPeriod:morning.id,ruleId:day0Rule.id}));
assert.match($('tt-board').innerHTML,/data-delete-card/);
const deleteIcon={dataset:{deleteCard:'',ruleId:day0Rule.id,boardDay:'0'}};
context.window.confirm=()=>false;
$('tt-board').onclick({target:{dataset:deleteIcon.dataset,closest:selector=>selector==='[data-delete-card]'?deleteIcon:null}});
assert.deepEqual(Array.from(day0Rule.weekdays),[0,6],'cancelled deletion leaves the lesson in place');
context.window.confirm=()=>true;
$('tt-board').onclick({target:{dataset:deleteIcon.dataset,closest:selector=>selector==='[data-delete-card]'?deleteIcon:null}});
assert.deepEqual(Array.from(day0Rule.weekdays),[6],'Delete lesson removes the selected board occurrence only');
assert.match($('tt-board-message').textContent,/period remains/);
planner.undo();
assert.deepEqual(Array.from(state.draft.rules.find(row=>row.id===day0Rule.id).weekdays),[0,6]);
$('tt-select-weekdays').onclick();
assert.match($('tt-availability-days').innerHTML,/value="5" checked/,'weekday shortcut selects Monday through Friday');
chooseAvailabilityDays([1,4,5]);
$('tt-availability-from').value='745';$('tt-availability-from').onchange({target:$('tt-availability-from')});
assert.equal($('tt-availability-from').value,'07h45');
$('tt-availability-to').value='830';$('tt-availability-to').onchange({target:$('tt-availability-to')});
assert.equal($('tt-availability-to').value,'08h30');
const availabilityBefore=state.draft.planner.availability.length;
$('tt-add-availability').onclick();
assert.equal(state.draft.planner.availability.length,availabilityBefore+3,'one range is applied to all selected days');
assert(state.draft.planner.availability.some(row=>row.weekday===5&&row.startTime==='07:45'));
assert.match($('tt-availability-grid').innerHTML,/07h45/);
chooseAvailabilityDays([1,6]);$('tt-availability-from').value='08h00';$('tt-availability-to').value='09h00';
$('tt-add-availability').onclick();
assert.equal(state.draft.planner.availability.length,availabilityBefore+3,'overlap on one day rejects the entire multi-day addition');
assert.match($('tt-availability-message').textContent,/Monday.*No days were added/);
assert(changes>=8);
// Teacher tabs show a seven-day availability board with multiple editable ranges and drag-to-copy.
assert.match($('tt-availability-grid').innerHTML,/tt-availability-board/);
assert.equal([...$('tt-availability-grid').innerHTML.matchAll(/<th scope="col">/g)].length,7);
const availabilityTarget=(selector,dataset)=>({target:{closest:key=>key===selector?{dataset}:null}});
$('tt-availability-tabs').onclick(availabilityTarget('[data-availability-teacher]',{availabilityTeacher:'TEACHER-2'}));
assert.equal($('tt-availability-teacher').value,'TEACHER-2');
assert.match($('tt-availability-grid').innerHTML,/No ranges set · no availability restriction/);
assert.match($('tt-availability-grid').innerHTML,/tt-availability-plus/);
const addAvailabilityDay=day=>$('tt-availability-grid').onclick(availabilityTarget('[data-add-availability-day]',{addAvailabilityDay:String(day)}));
addAvailabilityDay(0);
assert.equal($('tt-availability-dialog').open,true);
$('tt-availability-dialog-from').value='745';$('tt-availability-dialog-from').onchange({target:$('tt-availability-dialog-from')});
$('tt-availability-dialog-to').value='830';$('tt-availability-dialog-to').onchange({target:$('tt-availability-dialog-to')});
assert.equal($('tt-availability-dialog-from').value,'07h45');
$('tt-availability-save').onclick();
assert.equal($('tt-availability-dialog').open,false);
const sundayRange=state.draft.planner.availability.find(row=>row.teacherId==='TEACHER-2'&&row.weekday===0);
assert.deepEqual([sundayRange.startTime,sundayRange.endTime],['07:45','08:30']);
$('tt-availability-grid').onclick(availabilityTarget('[data-availability-day]',{availabilityDay:'0'}));
$('tt-availability-dialog-from').value='900';$('tt-availability-dialog-to').value='1000';$('tt-availability-save').onclick();
assert.equal(state.draft.planner.availability.filter(row=>row.teacherId==='TEACHER-2'&&row.weekday===0).length,2);
$('tt-availability-grid').onclick(availabilityTarget('[data-edit-availability]',{editAvailability:sundayRange.id}));
assert.equal($('tt-availability-dialog').open,true);
$('tt-availability-dialog-from').value='730';$('tt-availability-save').onclick();
assert.equal(sundayRange.startTime,'07:30');
let availabilityDragId='';const availabilityTransfer={setData:(type,id)=>{if(type==='application/x-m4l-availability')availabilityDragId=id;},getData:()=>availabilityDragId};
$('tt-availability-grid').ondragstart({...availabilityTarget('[data-availability-range]',{availabilityRange:sundayRange.id}),dataTransfer:availabilityTransfer});
const dropAvailability=day=>$('tt-availability-grid').ondrop({...availabilityTarget('[data-availability-day]',{availabilityDay:String(day)}),dataTransfer:availabilityTransfer,preventDefault(){}});
dropAvailability(6);
const copiedRange=state.draft.planner.availability.find(row=>row.teacherId==='TEACHER-2'&&row.weekday===6);
assert(copiedRange&&copiedRange.id!==sundayRange.id&&copiedRange.startTime==='07:30','dragging copies the range without removing its source');
dropAvailability(6);
assert.equal(state.draft.planner.availability.filter(row=>row.teacherId==='TEACHER-2'&&row.weekday===6).length,1,'overlapping drag copies are rejected');
context.window.confirm=()=>false;
$('tt-availability-grid').onclick(availabilityTarget('[data-remove-availability]',{removeAvailability:copiedRange.id}));
assert(state.draft.planner.availability.some(row=>row.id===copiedRange.id),'cancel keeps the range');
context.window.confirm=()=>true;
$('tt-availability-grid').onclick(availabilityTarget('[data-remove-availability]',{removeAvailability:copiedRange.id}));
assert.equal(state.draft.planner.availability.some(row=>row.id===copiedRange.id),false);
$('tt-availability-tabs').onclick(availabilityTarget('[data-availability-teacher]',{availabilityTeacher:'TEACHER-1'}));
assert.match($('tt-availability-grid').innerHTML,/Demo teacher A/);
// A lesson covering two planning periods occupies one board cell and can be split for one weekday.
const doubleRule=(id,weekdays,startTime,endTime,teacherId='')=>({id,moduleId:'MOD-DEMO',programSubjectId:'PS-TAFSEER',teacherId,classIds:['CLASS-1'],weekdays,startTime,endTime,zoomLink:''});
state.draft.rules=[doubleRule('RULE-DOUBLE',[3,4],'08:00','10:00'),doubleRule('RULE-EARLY',[5,6],'08:00','09:00'),doubleRule('RULE-LATE',[5],'09:00','10:00')];
state.draft.planner.periods=[{id:'PERIOD-DOUBLE-1',startTime:'08:00',endTime:'09:00'},{id:'PERIOD-DOUBLE-2',startTime:'09:00',endTime:'10:00'}];
state.draft.planner.availability=[];state.draft.planner.limits=[];delete state.draft.breaks;
$('tt-board-view').onchange({target:{value:'class'}});$('tt-board-class').onchange({target:{value:'CLASS-1'}});planner.render();
const doubleStart=state.draft.planner.periods[0],doubleBoard=$('tt-board').innerHTML;
assert.match(doubleBoard,/<td class="tt-board-spanning" rowspan="2"><div draggable="true"[^>]*data-board-day="3"[^>]*data-rule-id="RULE-DOUBLE"/);
assert.equal([...doubleBoard.matchAll(/<div draggable="true"[^>]*data-board-day="3"[^>]*data-rule-id="RULE-DOUBLE"/g)].length,1,'the Wednesday double lesson is shown only once');
$('tt-board').onclick(event({boardDay:'3',boardPeriod:doubleStart.id,ruleId:'RULE-DOUBLE'}));
assert.equal($('tt-quick-lesson-dialog').open,true);
assert.equal($('tt-quick-split').hidden,false,'Split is offered for a spanning lesson');
$('tt-quick-split').onclick();
assert.equal($('tt-quick-lesson-dialog').open,false);
assert.deepEqual(state.draft.rules.filter(row=>row.weekdays.includes(3)).map(row=>[row.startTime,row.endTime]),[['08:00','09:00'],['09:00','10:00']]);
assert.deepEqual(Array.from(state.draft.rules.find(row=>row.id==='RULE-DOUBLE').weekdays),[4],'splitting Wednesday leaves Thursday combined');
assert.equal(validateWeeklyTimetable(state.draft,f.catalog,f.program,'2026-09-29').valid,true,'the split remains publishable');
planner.undo();
assert.deepEqual(Array.from(state.draft.rules.find(row=>row.id==='RULE-DOUBLE').weekdays),[3,4]);
dragLesson('RULE-DOUBLE',3,2,doubleStart.id);
assert(state.draft.rules.some(row=>row.weekdays.length===1&&row.weekdays[0]===2&&row.startTime==='08:00'&&row.endTime==='10:00'),'dragging a double lesson preserves both periods');
planner.undo();
$('tt-board').onclick(event({boardDay:'5',boardPeriod:doubleStart.id,ruleId:'RULE-EARLY'}));
assert.equal($('tt-quick-merge-next').hidden,false,'Merge is offered for matching consecutive lessons');
$('tt-quick-merge-next').onclick();
assert.deepEqual(state.draft.rules.filter(row=>row.weekdays.includes(5)).map(row=>[row.startTime,row.endTime]),[['08:00','10:00']]);
assert.deepEqual(Array.from(state.draft.rules.find(row=>row.id==='RULE-EARLY').weekdays),[6],'merging Friday leaves Sunday separate');
assert.equal(validateWeeklyTimetable(state.draft,f.catalog,f.program,'2026-09-29').valid,true,'the merged lesson remains publishable');
assert.match($('tt-board').innerHTML,/<td class="tt-board-spanning" rowspan="2"><div draggable="true"[^>]*data-board-day="5"/);
planner.undo();
$('tt-board').onclick(event({boardDay:'5',boardPeriod:state.draft.planner.periods[1].id,ruleId:'RULE-LATE'}));
assert.equal($('tt-quick-merge-previous').hidden,false,'Merge is also offered from the later period');
$('tt-quick-merge-previous').onclick();
assert.deepEqual(state.draft.rules.filter(row=>row.weekdays.includes(5)).map(row=>[row.startTime,row.endTime]),[['08:00','10:00']]);
planner.undo();
state.draft.rules.find(row=>row.id==='RULE-LATE').teacherId='TEACHER-2';planner.render();
$('tt-board').onclick(event({boardDay:'5',boardPeriod:doubleStart.id,ruleId:'RULE-EARLY'}));
assert.equal($('tt-quick-merge-next').hidden,true,'different teachers cannot be silently merged');
$('tt-quick-cancel').onclick();
// When planning periods have a gap, splitting omits that gap from teaching time.
state.draft.rules=[doubleRule('RULE-GAPPED',[3],'08:00','10:00')];
state.draft.planner.periods[1].startTime='09:15';state.draft.planner.periods[1].endTime='10:15';planner.render();
assert.match($('tt-board').innerHTML,/<td class="tt-board-spanning" rowspan="2"><div draggable="true"[^>]*data-board-day="3"/);
$('tt-board').onclick(event({boardDay:'3',boardPeriod:doubleStart.id,ruleId:'RULE-GAPPED'}));
$('tt-quick-split').onclick();
assert.deepEqual(state.draft.rules.map(row=>[row.startTime,row.endTime]),[['08:00','09:00'],['09:15','10:00']]);
assert.match($('tt-board-message').textContent,/gap between them is excluded/);
// A break saved between planning periods must have its own visible board row.
state.draft.rules.push(doubleRule('RULE-ACROSS-GAP',[4],'08:00','10:00'));
state.draft.breaks=[{id:'BREAK-SAVED',label:'Morning break',weekdays:[1,2],startTime:'09:00',endTime:'09:15'}];
planner.render();
const boardWithSavedBreak=$('tt-board').innerHTML;
assert.match(boardWithSavedBreak,/<th scope="row" class="tt-board-gap-heading"><strong>Break<\/strong><span>09h00–09h15<\/span><\/th>/);
assert.equal([...boardWithSavedBreak.matchAll(/data-break-id="BREAK-SAVED"/g)].length,2,'the saved break appears on both selected weekdays');
assert.match(boardWithSavedBreak,/<td class="tt-board-spanning" rowspan="3"><div draggable="true"[^>]*data-board-day="4"/,'a lesson spanning the gap still has one merged cell');
assert.match(boardWithSavedBreak,/2 periods<\/span>/,'the merged lesson counts teaching periods, not the gap row');
$('tt-board').onclick(event({boardDay:'1',breakId:'BREAK-SAVED'}));
assert.equal($('tt-break-editor').hidden,false,'the saved break can be edited from its gap row');
assert.equal($('tt-break-start').value,'09h00');
$('tt-mark-break').onclick();$('tt-board-break-label').value='Morning break';
assert.match($('tt-board').innerHTML,/data-break-gap-start="09:00"/);
$('tt-board').onclick(event({boardDay:'3',breakGapStart:'09:00',breakGapEnd:'09:15'}));
assert.deepEqual(Array.from(state.draft.breaks[0].weekdays),[1,2,3],'the gap row can mark the same break on another weekday');
$('tt-mark-break').onclick();
$('tt-board').onclick(event({boardDay:'3',breakId:'BREAK-SAVED'}));
$('tt-break-label').value='Wednesday break';$('tt-save-break').onclick();
assert(state.draft.breaks.some(row=>row.label==='Wednesday break'&&row.weekdays.length===1&&row.weekdays[0]===3),'a break between periods can be edited from the board');
$('tt-board-view').onchange({target:{value:'teacher'}});$('tt-board-teacher').onchange({target:{value:'TEACHER-1'}});
assert.match($('tt-board').innerHTML,/data-break-id="BREAK-SAVED"/,'the saved break also appears on a teacher board');
$('tt-board-view').onchange({target:{value:'class'}});
// The board caption changes only its own tab without opening a browser tab.
$('tt-add-board-tab').onclick();
const tabsBeforeViewChange=$('tt-board-tabs').innerHTML,tabIdsForView=[...tabsBeforeViewChange.matchAll(/data-board-tab="([^"]+)"/g)].map(match=>match[1]);
assert.equal(tabIdsForView.length,2);
const firstTabLabel=/<button[^>]*data-board-tab="[^"]+"[^>]*>([^<]*)<\/button>/.exec(tabsBeforeViewChange)[1];
assert.match($('tt-board').innerHTML,/data-edit-board-view/);
const editBoardView={dataset:{editBoardView:''}};
const openBoardView=()=>$('tt-board').onclick({target:{dataset:editBoardView.dataset,closest:selector=>selector==='[data-edit-board-view]'?editBoardView:null}});
$('tt-board').scrollTop=120;$('tt-board').scrollLeft=90;openBoardView();
assert.equal($('tt-board-view-dialog').open,true);
$('tt-tab-view').value='teacher';$('tt-tab-view').onchange();
$('tt-tab-view-save').onclick();
assert.equal($('tt-board-view-dialog').open,true,'a teacher must be selected');
assert.match($('tt-tab-view-error').textContent,/Choose a teacher/);
$('tt-tab-view-teacher').value='TEACHER-1';$('tt-tab-view-save').onclick();
assert.equal($('tt-board-view-dialog').open,false);
assert.match($('tt-board').innerHTML,/Teacher:/);
assert.match($('tt-board-tabs').innerHTML,/Teacher:/);
assert.equal($('tt-board').scrollTop,120);assert.equal($('tt-board').scrollLeft,90);
assert.equal(/<button[^>]*data-board-tab="[^"]+"[^>]*>([^<]*)<\/button>/.exec($('tt-board-tabs').innerHTML)[1],firstTabLabel,'the other tab keeps its view');
openBoardView();$('tt-tab-view').value='class';$('tt-tab-view').onchange();$('tt-tab-view-class').value='CLASS-2';$('tt-tab-view-save').onclick();
assert.match($('tt-board').innerHTML,/Class:/);
assert.match($('tt-board-tabs').innerHTML,/Class:/);
openBoardView();let boardEscapePrevented=false;
$('tt-board-view-dialog').oncancel({preventDefault(){boardEscapePrevented=true;}});
assert.equal(boardEscapePrevented,true);assert.equal($('tt-board-view-dialog').open,false);
// A teacher booked on another class is identified only when a conflicting lesson is attempted.
state.draft.rules=[{...doubleRule('RULE-OTHER-CLASS',[3],'09:15','10:15','TEACHER-2'),classIds:['CLASS-2']}];
$('tt-board-class').onchange({target:{value:'CLASS-1'}});
$('tt-board-subject').onchange({target:{value:'MOD-DEMO'}});
$('tt-board-teacher').onchange({target:{value:'TEACHER-2'}});
assert.doesNotMatch($('tt-board').innerHTML,/already teaches|tt-board-cell-error/,'empty cells do not show speculative clashes');
$('tt-board').onclick(event({boardDay:'3',boardPeriod:state.draft.planner.periods[1].id}));
assert.equal(state.draft.rules.length,1);
assert.match($('tt-board-message').textContent,/Demo teacher B already teaches Year 2 · Demo on Wednesday 09h15–10h15/);
assert.equal(($('tt-board').innerHTML.match(/tt-board-cell-error/g)||[]).length,1,'the clash appears only in the attempted cell');
const syncSource=await readFile(new URL('../../js/m4l-timetable-sync.js',import.meta.url),'utf8');
const syncContext={window:{},structuredClone};vm.runInNewContext(syncSource,syncContext);
const merge=syncContext.window.M4L_TIMETABLE_SYNC.merge;
const base={format:'weekly',rules:[{id:'A',teacherId:'T1',startTime:'08:00'}],planner:{periods:[]}};
const ours=structuredClone(base),theirs=structuredClone(base);
ours.rules.push({id:'B',teacherId:'',startTime:'09:00'});
theirs.rules[0].teacherId='T2';
const combined=merge(base,ours,theirs);
assert.equal(combined.rules.length,2,'different boards can add and edit lessons together');
assert.equal(combined.rules[0].teacherId,'T2');
const competing=structuredClone(base);competing.rules[0].teacherId='T3';
assert.throws(()=>merge(base,theirs,competing),/same timetable item/,'same-field edits from two tabs cannot overwrite one another');
assert.throws(()=>merge(base,{...base,rules:[]},theirs),/same timetable item/,'deletion cannot silently discard another tab’s edit');
console.log('Assisted planner: in-page tabs, board view picker, merged cells, lesson split and merge, drag movement, availability, breaks and undo passed.');
