import assert from 'node:assert/strict';
import { timetableFixture } from '../../scripts/program-timetable-fixtures.mjs';
import { timetableService } from '../src/programs/timetable-service.js';
import { timetableCoordinator } from '../src/programs/timetable-coordination.js';
import { applyManagementChange, managementState } from '../src/programs/management-model.js';
const f=timetableFixture(),service=timetableService(f.repository,f.program);
let authorized=true;
const coordinator=timetableCoordinator(f.journal,async()=>{if(!authorized)throw new Error('revoked');return {service,user:{accountid:'ADMIN'}};});
let view=await service.read('manage-get');
const input=(record,kind='classes',creating=true)=>({id:f.program.id,operationId:crypto.randomUUID(),revision:view.revision,referenceRevision:view.referenceRevision,kind,record,creating});
await coordinator.run('manage-save',input({ClassID:'CLS-1',Name:'Evening',Active:true}),'token');
const firstPlan=structuredClone(f.plans[0]);
view=await service.read('manage-get');
const requests=[input({ClassID:'CLS-2',Name:'Morning',Active:true}),input({ClassID:'CLS-3',Name:'Weekend',Active:true})];
const outcomes=await Promise.allSettled(requests.map(r=>coordinator.run('manage-save',r,'token')));
assert.equal(outcomes.filter(r=>r.status==='fulfilled').length,1);
view=await service.read('manage-get');assert.equal(view.rows.classes.length,4);
await f.repository.apply(firstPlan);assert.equal((await service.read('manage-get')).revision,view.revision);
const uncertain=input({ClassID:'CLS-RETRY',Name:'Retry',Active:true});f.failNext('before');
await assert.rejects(coordinator.run('manage-save',uncertain,'token'),/Injected/);
authorized=false;await assert.rejects(coordinator.run('recover',{id:f.program.id},'token'),/revoked/);
authorized=true;await coordinator.run('recover',{id:f.program.id},'token');
assert((await coordinator.run('manage-save',uncertain,'token')).replayed);
assert.equal((await service.read('manage-get')).rows.classes.filter(r=>r.ClassID==='CLS-RETRY').length,1);
view=await service.read('manage-get');
await assert.rejects(coordinator.run('manage-save',input({ProgramSubjectID:'PS-ARABIC',SubjectID:'ARABIC',Active:'true'},'subjects'),'token'),/Active or Archived/);
await coordinator.run('manage-save',input({ProgramSubjectID:'PS-ARABIC',SubjectID:'ARABIC',Active:true},'subjects'),'token');
view=await service.read('manage-get');
await coordinator.run('manage-save',input({LevelID:'LVL-ARABIC',ProgramSubjectID:'PS-ARABIC',Name:'L1',Active:true},'levels'),'token');
view=await service.read('manage-get');
await assert.rejects(coordinator.run('manage-save',input({ProgramModuleID:'MOD-WRONG',ProgramSubjectID:'PS-TAFSEER',LevelID:'LVL-ARABIC',Name:'Wrong scope',Active:true},'modules'),'token'),/level must belong/);
await assert.rejects(coordinator.run('manage-save',input({ProgramSubjectID:'PS-DUP',SubjectID:'ARABIC',Active:true},'subjects'),'token'),/already linked/);
f.program.status='ARCHIVED';await assert.rejects(coordinator.run('manage-save',input({ClassID:'CLS-BLOCK',Name:'Blocked',Active:true}),'token'),/Archived/);f.program.status='DRAFT';
const state=managementState(await f.repository.load(),f.program),refs=await f.repository.managementReferences();
assert.throws(()=>applyManagementChange(state,{kind:'classes',creating:true,record:{ClassID:'CLS-X',Name:'Evening',Active:true}},refs,f.program),/name already exists/);
const foreign=structuredClone(await f.repository.load());foreign.tables.ProgramManagementState[0].CourseID='OTHER';assert.throws(()=>managementState(foreign,f.program),/history needs repair/);
console.log('Program management: shared subjects, level scope, duplicates, archive guards, authority, concurrent edits, recovery and late-write preservation passed.');
