import assert from 'node:assert/strict';
import vm from 'node:vm';
import { readFile } from 'node:fs/promises';
import { timetableFixture } from '../../scripts/program-timetable-fixtures.mjs';
import { timetableService } from '../src/programs/timetable-service.js';
import { timetableCoordinator } from '../src/programs/timetable-coordination.js';

const markup=await readFile(new URL('../../programs/library.html',import.meta.url),'utf8');
const source=await readFile(new URL('../../js/m4l-program-library.js',import.meta.url),'utf8');
assert(markup.indexOf('id="pl-add-drive"')<markup.indexOf('<section id="pl-bulk"'));
assert(markup.indexOf('<section id="pl-bulk"')<markup.indexOf('<section id="pl-editor"'));
assert(markup.indexOf('<section id="pl-editor"')<markup.indexOf('<section id="pl-list"'),'Review and editor appear above the resource catalogue');
assert(markup.indexOf('id="pl-bulk-start"')<markup.indexOf('id="pl-bulk-subject"'),'Review controls appear before the fields');
assert(markup.indexOf('id="pl-save"')<markup.indexOf('id="pl-type"'),'Editor controls appear before the fields');
const ids=new Set([...markup.matchAll(/id="([^"]+)"/g)].map(match=>match[1]));
const elements=new Map(),storage=new Map(),requests=[];
function element(id){
  assert(ids.has(id),`Missing Library element ${id}`);
  if(!elements.has(id))elements.set(id,{hidden:false,open:false,disabled:false,value:'',textContent:'',innerHTML:'',dataset:{},listeners:{},classList:{toggle(){}},focus(){this.focused=true;},click(){this.clicked=true;},removeAttribute(name){delete this[name];},showModal(){this.open=true;},close(){this.open=false;this.onclose?.();},addEventListener(type,fn){this.listeners[type]=fn;}});
  return elements.get(id);
}
const f=timetableFixture(),service=timetableService(f.repository,f.program);
f.repository.verifyResource=async row=>({id:row.DriveFileID});
f.repository.verifyCover=async row=>({id:row.CoverDriveFileID});
f.repository.verifyLibraryRoot=async value=>({FolderID:value,Name:'Second Drive folder'});
const coordinator=timetableCoordinator(f.journal,async()=>({service,user:{accountid:'ADMIN'}}));
let failSave=false,lastUploadType='',lastUploadName='',multiChunkUpload=false,rateLimitedChunkOnce=false,destinationId='resources-folder-123';
class TestFile extends Blob { constructor(parts,name,options){super(parts,options);this.name=name;} }
const context={console,URL,URLSearchParams,structuredClone,crypto,File:TestFile,
  location:{search:`?program=${f.program.id}`},window:{M4L_CONFIG:{API_BASE:''}},document:{getElementById:element},
  localStorage:{getItem:()=> 'token'},sessionStorage:{getItem:key=>storage.get(key)||null,setItem:(key,value)=>storage.set(key,value),removeItem:key=>storage.delete(key)},
  fetch:async(url,options)=>{
    if(url.endsWith('/upload-chunk')){
      const offset=Number(options.headers['X-Library-Upload-Offset']);
      requests.push({action:'upload-chunk',offset,body:options.body});
      if(multiChunkUpload&&offset===0)return {ok:true,status:200,json:async()=>({success:true,complete:false,nextOffset:4194304})};
      if(rateLimitedChunkOnce&&offset===4194304){rateLimitedChunkOnce=false;return {ok:false,status:503,json:async()=>({success:false,code:'SHEETS_RATE_LIMITED',retryAfterMs:60000,error:'Google Sheets is temporarily limiting requests.'})};}
      return {ok:true,status:200,json:async()=>({success:true,complete:true,nextOffset:123,file:lastUploadName.startsWith('Bulk')?{id:`bulk-${lastUploadName.replace(/[^A-Za-z0-9_-]/g,'-')}`,name:lastUploadName,mimeType:lastUploadType==='COVER'?'image/png':'application/pdf'}:lastUploadType==='COVER'?{id:'uploaded-cover',name:'Device-cover.png',mimeType:'image/png'}:{id:'uploaded-pdf',name:'Device.pdf',mimeType:'application/pdf'}})};
    }
    const action=url.split('/').at(-1),body=JSON.parse(options.body);requests.push({action,body});
    if(action==='upload-start'){lastUploadType=body.resourceType;lastUploadName=body.fileName;return {ok:true,status:200,json:async()=>({success:true,ticket:'ticket',chunkSize:4194304})};}
    if(action==='browse')return {ok:true,status:200,json:async()=>({success:true,folder:{id:body.folderId||destinationId,name:'Resources'},breadcrumbs:[{id:destinationId,name:'Resources'}],items:[{id:'file-pdf',name:'Lesson.pdf',mimeType:'application/pdf',isFolder:false,supportedTypes:['EBOOK'],format:'PDF'},{id:'file-pdf-2',name:'Second.pdf',mimeType:'application/pdf',isFolder:false,supportedTypes:['EBOOK','PRINTABLE'],format:'PDF'},{id:'file-pdf-3',name:'Third.pdf',mimeType:'application/pdf',isFolder:false,supportedTypes:['EBOOK','PRINTABLE'],format:'PDF'},{id:'file-audio',name:'Recording.mp3',mimeType:'audio/mpeg',isFolder:false,supportedTypes:['AUDIO'],format:'MP3'},{id:'cover-png',name:'Cover.png',mimeType:'image/png',isFolder:false,supportedTypes:['OTHER'],format:'PNG'},{id:'folder-one',name:'Folder one',isFolder:true,supportedTypes:[],format:''}],nextPageToken:''})};
    if(action==='save'&&failSave){failSave=false;throw new Error('Offline');}
    if(action==='folder-set'){destinationId='new-resources-folder-123';return {ok:true,status:200,json:async()=>({success:true,folder:{id:destinationId,name:'New Resources'}})};}
    try{
      const result=['save','recover'].includes(action)?await coordinator.run(action==='save'?'manage-save':action,body,'token'):await service.read(action==='manage'?'manage-get':action,body);
      return {ok:true,status:200,json:async()=>({success:true,coordinatorAvailable:true,canManageFolder:true,destinationId,...result})};
    }catch(error){return {ok:false,status:error.status||503,json:async()=>({success:false,error:error.message,code:error.code})};}
  }
};
const settled=async()=>{for(let i=0;i<12;i++)await new Promise(resolve=>setTimeout(resolve,1));};
vm.runInNewContext(source,context);await settled();
assert.equal(element('pl-add-device').disabled,false);
assert.equal(element('pl-add-drive').disabled,false);
element('pl-add-drive').onclick();await settled();
assert.equal(element('pl-drive').open,true,'The top Library Drive action opens the Resources finder as a modal dialog');
element('pl-drive').onclick({target:{closest:selector=>selector==='[data-folder]'?{dataset:{folder:'folder-one'}}:null}});await settled();
assert.equal(requests.filter(row=>row.action==='browse').at(-1).body.folderId,'folder-one');
element('pl-drive').onclick({target:{closest:selector=>selector==='[data-file]'?{dataset:{file:'file-pdf'}}:null}});
assert.equal(element('pl-drive').open,false,'Choosing one file opens its review row');
assert.equal(element('pl-bulk').hidden,false);
assert.match(element('pl-bulk-list').innerHTML,/Lesson\.pdf/);
element('pl-bulk-subject').onchange({target:{value:'PS-TAFSEER'}});
await element('pl-bulk-start').onclick();await settled();
assert.equal((await service.read('manage-get')).rows.resources.length,1);
element('pl-bulk-cancel').onclick();
const firstId=(await service.read('manage-get')).rows.resources[0].ResourceID;
element('pl-list').onclick({target:{closest:selector=>selector==='[data-edit]'?{dataset:{edit:firstId}}:null}});
assert.equal(element('pl-name').value,'Lesson');
element('pl-type').listeners.change({target:{value:'AUDIO'}});
assert.match(element('pl-file').textContent,/file-pdf/);
element('pl-type').listeners.change({target:{value:'EBOOK'}});
element('pl-browse').onclick();await settled();
element('pl-drive').onclick({target:{closest:selector=>selector==='[data-file]'?{dataset:{file:'file-pdf'}}:null}});
failSave=true;element('pl-save').onclick();await settled();
assert.equal(element('pl-pending').hidden,false);
const pendingKey=`m4l-program-library-pending:${f.program.id}`,draftKey=`m4l-program-library-draft:${f.program.id}`;
const operation=JSON.parse(storage.get(pendingKey)).body.operationId;
storage.delete(draftKey);
vm.runInNewContext(source,context);await settled();
assert.equal(element('pl-editor').hidden,false,'A pending resource restores the editor without a separate draft');
element('pl-retry').onclick();await settled();
assert.equal((await service.read('manage-get')).rows.resources.length,1);
assert.equal(requests.filter(row=>row.action==='save').at(-1).body.operationId,operation);
assert.equal(storage.has(pendingKey),false);
assert.equal(element('pl-pending').hidden,true);
element('pl-add-drive').onclick();await settled();
element('pl-drive-cancel').onclick();
element('pl-folder-input').value='new-resources-folder-123';
element('pl-folder-save').onclick();await settled();
assert.equal(destinationId,'new-resources-folder-123');
assert.match(element('pl-destination').textContent,/new-resources-folder-123/);
assert.equal(element('pl-drive').open,false);
element('pl-add-device').onclick();
assert.equal(element('pl-device-file').clicked,true,'The top device action opens the native file picker');
assert.equal(element('pl-device-file').multiple,true,'The same picker accepts one or several files');
assert.match(element('pl-device-file').accept,/audio\/\*/,'The first picker allows files from every Library category');
element('pl-device-file').onchange({target:{files:[{name:'Device.pdf',type:'application/pdf',size:123,slice:()=>new Blob(['PDF'])}],value:'Device.pdf'}});await settled();
assert.equal(element('pl-bulk').hidden,false,'One selected device file opens one review row');
assert.match(element('pl-bulk-list').innerHTML,/Device\.pdf/);
element('pl-bulk-list').onchange({target:{dataset:{bulkIndex:'0',bulkField:'type'},value:'PRINTABLE'}});
assert.match(element('pl-bulk-list').innerHTML,/value="PRINTABLE" selected/,'Category can be changed before upload');
element('pl-bulk-list').onchange({target:{dataset:{bulkIndex:'0',bulkField:'type'},value:'EBOOK'}});
element('pl-bulk-subject').onchange({target:{value:'PS-TAFSEER'}});
await element('pl-bulk-start').onclick();await settled();
assert.equal(element('pl-bulk').hidden,false,'Review stays visible after saving');
element('pl-bulk-cancel').onclick();
const deviceRow=(await service.read('manage-get')).rows.resources.find(row=>row.DriveFileID==='uploaded-pdf');
assert(deviceRow,'The selected device file is uploaded and saved');
element('pl-list').onclick({target:{closest:selector=>selector==='[data-edit]'?{dataset:{edit:deviceRow.ResourceID}}:null}});
assert.equal(element('pl-save').disabled,false);
assert.equal(requests.filter(row=>row.action==='upload-start').at(-1).body.resourceType,'EBOOK');
element('pl-author').listeners.input({target:{value:'A. Author'}});
element('pl-publisher').listeners.input({target:{value:'A Publisher'}});
element('pl-isbn').listeners.input({target:{value:'978-1-23456-789-0'}});
element('pl-year').listeners.input({target:{value:'2025'}});
element('pl-cover-browse').onclick();await settled();
element('pl-drive').onclick({target:{closest:selector=>selector==='[data-file]'?{dataset:{file:'cover-png'}}:null}});
assert.equal(JSON.parse(storage.get(draftKey)).record.CoverDriveFileID,'cover-png');
assert.equal(JSON.parse(storage.get(draftKey)).record.Author,'A. Author');
element('pl-cover-device').onclick();assert.equal(element('pl-cover-device-file').clicked,true);
element('pl-cover-device-file').onchange({target:{files:[{name:'Device-cover.png',type:'image/png',size:12,slice:()=>new Blob(['image'])}],value:'Device-cover.png'}});await settled();
element('pl-upload').onclick();await settled();
assert.equal(requests.filter(row=>row.action==='upload-start').at(-1).body.resourceType,'COVER');
assert.equal(JSON.parse(storage.get(draftKey)).record.CoverDriveFileID,'uploaded-cover');
assert.equal(element('pl-save').disabled,false,'Saving is enabled after a cover upload finishes');
element('pl-cover-online').onclick();
assert.equal(element('pl-cover-search').open,true,'Online cover search opens a centered dialog');
assert.equal(element('pl-cover-title').value,element('pl-name').value,'The book title starts the manual image search');
assert.equal(element('pl-cover-author').value,'A. Author');
assert.equal(element('pl-cover-publisher').value,'A Publisher');
element('pl-cover-search-form').onsubmit({preventDefault(){}});await settled();
assert.equal(element('pl-cover-query').value,`${element('pl-name').value} A. Author A Publisher book cover`);
assert.match(markup,/action="https:\/\/www\.google\.com\/search"[^>]*target="_blank"/);
assert.match(markup,/name="tbm" value="isch"/);
element('pl-cover-device-file').clicked=false;
element('pl-cover-use-device').onclick();
assert.equal(element('pl-cover-search').open,false);
assert.equal(element('pl-cover-device-file').clicked,true,'A saved web image can use the existing cover upload');
assert.equal(JSON.parse(storage.get(draftKey)).record.CoverDriveFileID,'uploaded-cover');
assert.equal(requests.some(row=>['cover-search','cover-image'].includes(row.action)),false,'No external cover source is requested by the app');
element('pl-cover-paste').onclick();
assert.equal(element('pl-cover-search').open,true,'Paste cover opens the centered paste area');
assert.equal(element('pl-cover-paste-target').focused,true,'The paste area receives keyboard focus');
let pastePrevented=false;
element('pl-cover-paste-target').onpaste({clipboardData:{items:[{kind:'string',type:'text/plain'}]},preventDefault(){pastePrevented=true;}});
assert.equal(pastePrevented,true);
assert.match(element('pl-cover-paste-status').textContent,/No image was found/);
assert.equal(element('pl-cover-search').open,true,'Pasting a link keeps the dialog open');
const pastedImage=new Blob(['pasted image'],{type:'image/png'});
element('pl-cover-paste-target').onpaste({clipboardData:{items:[{kind:'file',type:'image/png',getAsFile:()=>pastedImage}]},preventDefault(){}});
assert.equal(element('pl-cover-search').open,false);
assert.equal(element('pl-drive').open,true,'A pasted image enters the existing cover upload flow');
assert.match(element('pl-drive-help').textContent,/book-cover-\d+\.png/);
element('pl-upload').onclick();await settled();
assert.equal(requests.filter(row=>row.action==='upload-start').at(-1).body.resourceType,'COVER');
assert.match(requests.filter(row=>row.action==='upload-start').at(-1).body.fileName,/^book-cover-\d+\.png$/);
assert.equal(JSON.parse(storage.get(draftKey)).record.CoverDriveFileID,'uploaded-cover');
multiChunkUpload=true;rateLimitedChunkOnce=true;
const startsBeforeResume=requests.filter(row=>row.action==='upload-start').length;
const chunksBeforeResume=requests.filter(row=>row.action==='upload-chunk').length;
element('pl-device').onclick();
element('pl-device-file').onchange({target:{files:[{name:'Large.pdf',type:'application/pdf',size:4194314,slice:()=>new Blob(['PDF'])}],value:'Large.pdf'}});await settled();
element('pl-upload').onclick();await settled();
assert.equal(element('pl-drive').open,true,'A rate limit keeps the destination dialog and file open');
assert.match(element('pl-drive-status').textContent,/continue from 99%/);
assert.equal(requests.filter(row=>row.action==='upload-start').length,startsBeforeResume+1);
assert.deepEqual(requests.filter(row=>row.action==='upload-chunk').slice(chunksBeforeResume).map(row=>row.offset),[0,4194304]);
element('pl-upload').onclick();await settled();
assert.equal(element('pl-drive').open,false,'Retrying the final chunk completes the upload');
assert.equal(element('pl-save').disabled,false,'Saving is enabled after a resumed upload finishes');
assert.equal(requests.filter(row=>row.action==='upload-start').length,startsBeforeResume+1,'Retry keeps the original Drive upload session');
assert.deepEqual(requests.filter(row=>row.action==='upload-chunk').slice(chunksBeforeResume).map(row=>row.offset),[0,4194304,4194304]);
element('pl-browse').onclick();await settled();
element('pl-drive').onclick({target:{closest:selector=>selector==='[data-file]'?{dataset:{file:'file-pdf'}}:null}});
assert.equal(JSON.parse(storage.get(draftKey)).record.DriveFileID,'file-pdf','An existing Resources file can be selected without copying');
assert.equal(element('pl-drive').open,false);
assert.equal(requests.some(row=>row.action==='copy'),false,'The shared-link copy action is absent');
element('pl-cancel').onclick();
element('pl-add-device').onclick();
element('pl-device-file').onchange({target:{files:[{name:'Lesson.mp3',type:'audio/mpeg',size:12,slice:()=>new Blob(['audio'])}],value:'Lesson.mp3'}});await settled();
assert.match(element('pl-bulk-list').innerHTML,/value="AUDIO" selected/,'A selected audio file sets the matching category');
element('pl-bulk-cancel').onclick();
multiChunkUpload=false;
element('pl-add-device').onclick();
assert.equal(element('pl-device-file').clicked,true,'The same Add from device button opens the native multi-file picker');
assert.equal(element('pl-device-file').multiple,true);
const bulkOne=new TestFile([new Uint8Array(4194314)],'Bulk-one.pdf',{type:'application/pdf'}),bulkTwo=new TestFile(['second PDF'],'Bulk-two.pdf',{type:'application/pdf'});
element('pl-device-file').onchange({target:{files:[bulkOne,bulkTwo],value:'Bulk-one.pdf'}});
assert.equal(element('pl-bulk').hidden,false);
assert.match(element('pl-bulk-list').innerHTML,/Bulk-one\.pdf/);
const uploadsBeforePlacement=requests.filter(row=>row.action==='upload-start').length;
await element('pl-bulk-start').onclick();
assert.equal(requests.filter(row=>row.action==='upload-start').length,uploadsBeforePlacement,'Books are not uploaded before a subject is selected');
element('pl-bulk-subject').onchange({target:{value:'PS-TAFSEER'}});
element('pl-bulk-list').oninput({target:{dataset:{bulkIndex:'0',bulkField:'name'},value:'First book'}});
element('pl-bulk-list').oninput({target:{dataset:{bulkIndex:'0',bulkField:'description'},value:'First description'}});
element('pl-bulk-list').oninput({target:{dataset:{bulkIndex:'1',bulkField:'author'},value:'Second author'}});
const bulkCover=new TestFile(['cover'],'Bulk-cover.png',{type:'image/png'});
element('pl-bulk-list').onchange({target:{dataset:{bulkCover:'0'},files:[bulkCover]}});
multiChunkUpload=true;rateLimitedChunkOnce=true;failSave=true;
const bulkStartsBefore=requests.filter(row=>row.action==='upload-start').length;
const bulkChunksBefore=requests.filter(row=>row.action==='upload-chunk').length;
await element('pl-bulk-start').onclick();
assert.match(element('pl-bulk-status').textContent,/continue from 99%/);
assert.match(element('pl-bulk-start').textContent,/Continue upload/);
assert.equal(storage.has(pendingKey),false,'No save is started before the PDF upload completes');
multiChunkUpload=false;
await element('pl-bulk-start').onclick();
assert.equal(element('pl-bulk-start').disabled,false,'An uncertain bulk save can be retried');
assert.match(element('pl-bulk-status').textContent,/paused at file 1/);
const bulkOperation=JSON.parse(storage.get(pendingKey)).body.operationId;
assert.equal(JSON.parse(storage.get(pendingKey)).body.record.Name,'First book');
assert.equal(JSON.parse(storage.get(pendingKey)).body.record.Description,'First description');
await element('pl-bulk-start').onclick();
assert.equal(storage.has(pendingKey),false);
assert.match(element('pl-bulk-status').textContent,/All 2 resources saved/);
assert.equal(requests.filter(row=>row.action==='upload-start').length,bulkStartsBefore+3,'Each PDF and the selected cover upload once');
assert.deepEqual(requests.filter(row=>row.action==='upload-chunk').slice(bulkChunksBefore,bulkChunksBefore+3).map(row=>row.offset),[0,4194304,4194304],'The interrupted PDF resumes at its last confirmed offset');
const bulkSaves=requests.filter(row=>row.action==='save'&&row.body.record.ResourceID.startsWith('RES-')).slice(-3);
assert.equal(bulkSaves[0].body.operationId,bulkOperation);
assert.equal(bulkSaves[1].body.operationId,bulkOperation,'Retry uses the same save operation');
assert.equal(bulkSaves[2].body.record.Author,'Second author');
assert.equal((await service.read('manage-get')).rows.resources.filter(row=>['First book','Bulk-two'].includes(row.Name)).length,2);
assert.equal(element('pl-bulk-start').disabled,true,'A completed batch cannot be saved again');
element('pl-bulk-cancel').onclick();
const uploadCountBeforeDrive=requests.filter(row=>row.action==='upload-start').length;
element('pl-add-drive').onclick();await settled();
assert.equal(element('pl-drive').open,true);
assert.match(element('pl-drive-list').innerHTML,/data-drive-select="file-pdf-2"/);
element('pl-drive').onchange({target:{dataset:{driveSelect:'file-pdf-2'},checked:true}});
element('pl-drive').onchange({target:{dataset:{driveSelect:'file-pdf-3'},checked:true}});
assert.equal(element('pl-drive-selected').disabled,false);
element('pl-drive-selected').onclick();
assert.equal(element('pl-drive').open,false);
assert.equal(element('pl-bulk').hidden,false);
assert.match(element('pl-bulk-list').innerHTML,/Second\.pdf/);
assert.match(element('pl-bulk-list').innerHTML,/Third\.pdf/);
element('pl-bulk-subject').onchange({target:{value:'PS-TAFSEER'}});
await element('pl-bulk-start').onclick();await settled();
assert.equal(requests.filter(row=>row.action==='upload-start').length,uploadCountBeforeDrive,'Library Drive selections are linked without re-uploading');
assert.equal((await service.read('manage-get')).rows.resources.filter(row=>['file-pdf-2','file-pdf-3'].includes(row.DriveFileID)).length,2);
element('pl-bulk-cancel').onclick();
element('pl-add-drive').onclick();await settled();
element('pl-drive-type').onchange({target:{value:'AUDIO'}});
element('pl-drive').onclick({target:{closest:selector=>selector==='[data-file]'?{dataset:{file:'file-audio'}}:null}});
assert.equal(element('pl-bulk').hidden,false,'One Drive audio file uses the same review screen');
assert.match(element('pl-bulk-list').innerHTML,/value="AUDIO" selected/);
element('pl-bulk-cancel').onclick();
assert.doesNotMatch(markup,/id="pl-bulk-add"/,'A separate bulk action is not shown');
element('pl-list').onclick({target:{closest:selector=>selector==='[data-edit]'?{dataset:{edit:deviceRow.ResourceID}}:null}});
assert.equal(element('pl-add-device').disabled,false,'The Add action stays available while editing');
element('pl-add-device').onclick();
element('pl-device-file').onchange({target:{files:[new TestFile(['another'],'Another.pdf',{type:'application/pdf'})],value:'Another.pdf'}});
assert.equal(element('pl-editor').hidden,true,'The new review temporarily hides the open editor');
element('pl-bulk-list').onclick({target:{closest:selector=>selector==='[data-bulk-cover-online]'?{dataset:{bulkCoverOnline:'0'}}:null}});
assert.equal(element('pl-cover-search').open,true,'Book cover search is available in the shared review');
assert.equal(element('pl-cover-title').value,'Another');
element('pl-cover-paste-target').onpaste({clipboardData:{items:[{kind:'file',type:'image/png',getAsFile:()=>new Blob(['cover'],{type:'image/png'})}]},preventDefault(){}});
assert.equal(element('pl-cover-search').open,false);
assert.match(element('pl-bulk-list').innerHTML,/book-cover-\d+\.png/);
element('pl-bulk-list').onclick({target:{closest:selector=>selector==='[data-bulk-cover-drive]'?{dataset:{bulkCoverDrive:'0'}}:null}});await settled();
assert.equal(element('pl-drive').open,true,'A cover can also be chosen from Library Drive');
element('pl-drive').onclick({target:{closest:selector=>selector==='[data-file]'?{dataset:{file:'cover-png'}}:null}});
assert.equal(element('pl-drive').open,false);
assert.match(element('pl-bulk-list').innerHTML,/Cover selected/);
element('pl-bulk-cancel').onclick();
assert.equal(element('pl-editor').hidden,false,'Closing review restores the open editor');
assert.equal(element('pl-name').value,deviceRow.Name,'The existing editor draft is kept');
console.log('Program Library UI: one or many device and Drive files share review, with upload and retry recovery passed.');
