import assert from 'node:assert/strict';
import { timetableFixture } from '../../scripts/program-timetable-fixtures.mjs';
import { timetableService } from '../src/programs/timetable-service.js';
import { timetableCoordinator } from '../src/programs/timetable-coordination.js';
import { applyManagementChange, managementState } from '../src/programs/management-model.js';
const f=timetableFixture(),service=timetableService(f.repository,f.program);
let authorized=true;
const coordinator=timetableCoordinator(f.journal,async()=>{if(!authorized)throw new Error('revoked');return {service,user:{accountid:'ADMIN'}};});
let view=await service.read('manage-get');
const input=(record,kind='classes',creating=true)=>({id:f.program.id,operationId:crypto.randomUUID(),revision:view.revision,referenceRevision:view.referenceRevision,kind,record,creating});
await coordinator.run('manage-save',input({ClassID:'CLS-1',Name:'Evening',TeacherAccountID:'TEACHER-1',Active:true}),'token');
assert.equal((await service.read('get')).catalog.classes.find(row=>row.id==='CLS-1').classTeacherId,'TEACHER-1');
view=await service.read('manage-get');
await assert.rejects(coordinator.run('manage-save',input({ClassID:'CLS-NO-ROLE',Name:'No role',TeacherAccountID:'LEARNER-DEMO',Active:true}),'token'),/Teacher, Senior or Admin role/);
const firstPlan=structuredClone(f.plans[0]);
view=await service.read('manage-get');
const requests=[input({ClassID:'CLS-2',Name:'Morning',Active:true}),input({ClassID:'CLS-3',Name:'Weekend',Active:true})];
const outcomes=await Promise.allSettled(requests.map(r=>coordinator.run('manage-save',r,'token')));
assert.equal(outcomes.filter(r=>r.status==='fulfilled').length,1);
view=await service.read('manage-get');assert.equal(view.rows.classes.length,4);
await f.repository.apply(firstPlan);assert.equal((await service.read('manage-get')).revision,view.revision);
const uncertain=input({ClassID:'CLS-RETRY',Name:'Retry',Active:true});f.failNext('before');
await assert.rejects(coordinator.run('manage-save',uncertain,'token'),/Injected/);
authorized=false;await assert.rejects(coordinator.run('recover',{id:f.program.id},'token'),/revoked/);
authorized=true;await coordinator.run('recover',{id:f.program.id},'token');
assert((await coordinator.run('manage-save',uncertain,'token')).replayed);
assert.equal((await service.read('manage-get')).rows.classes.filter(r=>r.ClassID==='CLS-RETRY').length,1);
view=await service.read('manage-get');
await assert.rejects(coordinator.run('manage-save',input({ProgramSubjectID:'PS-ARABIC',SubjectID:'ARABIC',Active:'true'},'subjects'),'token'),/Active or Archived/);
await coordinator.run('manage-save',input({ProgramSubjectID:'PS-ARABIC',SubjectID:'ARABIC',Active:true},'subjects'),'token');
view=await service.read('manage-get');
await coordinator.run('manage-save',input({LevelID:'LVL-ARABIC',ProgramSubjectID:'PS-ARABIC',Name:'L1',Active:true},'levels'),'token');
view=await service.read('manage-get');
await assert.rejects(coordinator.run('manage-save',input({ProgramModuleID:'MOD-WRONG',ProgramSubjectID:'PS-TAFSEER',LevelID:'LVL-ARABIC',Name:'Wrong scope',Active:true},'modules'),'token'),/level must belong/);
await assert.rejects(coordinator.run('manage-save',input({ProgramSubjectID:'PS-DUP',SubjectID:'ARABIC',Active:true},'subjects'),'token'),/already linked/);
f.program.status='ARCHIVED';await assert.rejects(coordinator.run('manage-save',input({ClassID:'CLS-BLOCK',Name:'Blocked',Active:true}),'token'),/Archived/);f.program.status='DRAFT';
const state=managementState(await f.repository.load(),f.program),refs=await f.repository.managementReferences();
assert.throws(()=>applyManagementChange(state,{kind:'classes',creating:true,record:{ClassID:'CLS-X',Name:'Evening',Active:true}},refs,f.program),/name already exists/);
const foreign=structuredClone(await f.repository.load());foreign.tables.ProgramManagementState[0].CourseID='OTHER';assert.throws(()=>managementState(foreign,f.program),/history needs repair/);
// Bulk imports append missing links atomically and never replace archived/dependent rows.
const batch=timetableFixture(),bs=timetableService(batch.repository,batch.program);
const bc=timetableCoordinator(batch.journal,async()=>({service:bs,user:{accountid:'ADMIN'}}));
batch.shared.subjects.push({SubjectID:'FIQH',SubjectName:'Fiqh',Active:true},{SubjectID:'HADITH',SubjectName:'Hadith',Active:true},{SubjectID:'OLD',SubjectName:'Archived',Active:false},{SubjectID:'LEGACY',SubjectName:'Old course',Active:true,Legacy:true});
const original=structuredClone(managementState(await batch.repository.load(),batch.program).snapshot);
const bulk=async ids=>{const v=await bs.read('manage-get');return {id:batch.program.id,operationId:crypto.randomUUID(),revision:v.revision,referenceRevision:v.referenceRevision,kind:'subject-import',record:{subjectIds:ids}};};
for(const ids of [[],['MISSING'],['OLD'],['LEGACY'],['FIQH','MISSING'],Array(251).fill('FIQH')])await assert.rejects(bc.run('manage-save',await bulk(ids),'token'));
assert.deepEqual(managementState(await batch.repository.load(),batch.program).snapshot,original);
const one=await bulk(['FIQH']);
batch.failNext('after');await assert.rejects(bc.run('manage-save',one,'token'),/Injected/);
const replay=await bc.run('manage-save',one,'token');assert(replay.replayed);assert.equal(replay.record.added,1);
const multi=await bulk(['FIQH','ARABIC','ARABIC','HADITH']);
batch.failNext('before');await assert.rejects(bc.run('manage-save',multi,'token'),/Injected/);
assert((await bc.run('recover',{id:batch.program.id},'token')).recovered);
assert.deepEqual((await bc.run('manage-save',multi,'token')).record,{added:2,alreadyLinked:1,archived:0});
assert.deepEqual(await bc.run('recover',{id:batch.program.id},'token'),{recovered:false});
const saved=(await bs.read('manage-get')).rows.subjects;
assert.equal(saved.length,4);assert.equal(new Set(saved.map(r=>r.SubjectID)).size,4);
assert.deepEqual((await bc.run('manage-save',await bulk(['FIQH','ARABIC','HADITH']),'token')).record,{added:0,alreadyLinked:3,archived:0});
const after=managementState(await batch.repository.load(),batch.program).snapshot;
for(const key of Object.keys(original))if(key!=='ProgramSubjects')assert.deepEqual(after[key],original[key]);
const stale=await bulk(['FIQH']);await bc.run('manage-save',await bulk(['HADITH']),'token');
await assert.rejects(bc.run('manage-save',stale,'token'),/changed/);
const archived=structuredClone(after);archived.ProgramSubjects.find(r=>r.SubjectID==='FIQH').Active=false;
const unchanged=applyManagementChange({snapshot:archived},{kind:'subject-import',record:{subjectIds:['FIQH']}},batch.shared,batch.program);
assert.deepEqual(unchanged.record,{added:0,alreadyLinked:1,archived:1});assert.deepEqual(unchanged.snapshot,archived);
console.log('Program import: single/multiple selection, canonical deduplication, archived preservation, atomic failure, stale revisions and replay/recovery passed.');
console.log('Program management: shared subjects, level scope, duplicates, archive guards, authority, concurrent edits, recovery and late-write preservation passed.');

// Per-row revisions permit unrelated work while rejecting stale edits to the same row.
view=await service.read('manage-get');
const rowEdit=(record,creating=false)=>({...input(record,'classes',creating),baseRowRevision:view.rowRevisions.classes[record.ClassID]||view.emptyRowRevision});
const independent=[rowEdit({ClassID:'CLS-A',Name:'Independent A',Active:true},true),rowEdit({ClassID:'CLS-B',Name:'Independent B',Active:true},true)];
await Promise.all(independent.map(body=>coordinator.run('manage-save',body,'token')));
view=await service.read('manage-get');
const first=rowEdit({ClassID:'CLS-A',Name:'Renamed A',Active:true});
const conflict=rowEdit({ClassID:'CLS-A',Name:'Conflicting A',Active:true});
await coordinator.run('manage-save',first,'token');
await assert.rejects(coordinator.run('manage-save',conflict,'token'),error=>error.code==='ROW_CHANGED'&&error.currentRecord.Name==='Renamed A'&&Boolean(error.rowRevision));
const retained=rowEdit({ClassID:'CLS-B',Name:'Independent B updated',Active:true});
f.shared.accounts.push({AccountID:'UNRELATED',DisplayName:'Unrelated account',Active:true});
await coordinator.run('manage-save',retained,'token');
console.log('Row revisions: independent concurrent additions, unrelated references and same-row conflicts passed.');

// A student has one active class in a Program; changing it keeps the old record archived.
const groupFixture=timetableFixture(),groupService=timetableService(groupFixture.repository,groupFixture.program);
const groupCoordinator=timetableCoordinator(groupFixture.journal,async()=>({service:groupService,user:{accountid:'ADMIN'}}));
const groupInput=async(accountId,classId)=>{const current=await groupService.read('manage-get');return {id:groupFixture.program.id,operationId:crypto.randomUUID(),kind:'student-class',record:{AccountID:accountId,ClassID:classId},baseRowRevision:current.studentClassRevisions[accountId],revision:current.revision};};
const initialGroup=await groupInput('LEARNER-DEMO','CLASS-1');
await groupCoordinator.run('manage-save',initialGroup,'token');
let groupRows=(await groupService.read('manage-get')).rows.enrollments.filter(r=>r.AccountID==='LEARNER-DEMO');
assert.equal(groupRows.filter(r=>r.Active).length,1);assert.equal(groupRows.find(r=>r.Active).ClassID,'CLASS-1');
assert.equal(groupRows.filter(r=>!r.Active).length,2);
const staleGroup=await groupInput('LEARNER-DEMO','CLASS-2');
await groupCoordinator.run('manage-save',await groupInput('LEARNER-DEMO',''),'token');
await assert.rejects(groupCoordinator.run('manage-save',staleGroup,'token'),error=>error.code==='ROW_CHANGED'&&error.currentRecord.enrollments.every(r=>!r.Active));
const interruptedGroup=await groupInput('LEARNER-DEMO','CLASS-2');groupFixture.failNext('after');
await assert.rejects(groupCoordinator.run('manage-save',interruptedGroup,'token'),/Injected/);
await groupCoordinator.run('recover',{id:groupFixture.program.id},'token');
assert((await groupCoordinator.run('manage-save',interruptedGroup,'token')).replayed);
assert.equal((await groupService.read('manage-get')).rows.enrollments.filter(r=>r.AccountID==='LEARNER-DEMO'&&r.Active).length,1);
await assert.rejects(groupCoordinator.run('manage-save',await groupInput('TEACHER-1','CLASS-1'),'token'),/Student role/);
console.log('Student classes: one active class, archived history, clear, conflict, recovery and Student-role guard passed.');

view=await service.read('manage-get');
await assert.rejects(coordinator.run('manage-save',input({AccountID:'LEARNER-DEMO',Active:true},'teachers'),'token'),/needs an active Teacher/);
await coordinator.run('manage-save',input({AccountID:'TEACHER-1',Active:true},'teachers'),'token');
view=await service.read('manage-get');
f.shared.grantedTeachers=f.shared.grantedTeachers.filter(r=>r.AccountID!=='TEACHER-1');
await assert.rejects(coordinator.run('manage-save',input({AccountID:'TEACHER-1',Active:true},'teachers',false),'token'),/needs an active Teacher/);
await coordinator.run('manage-save',input({AccountID:'TEACHER-1',Active:false},'teachers',false),'token');
console.log('Teacher eligibility: current program role required; revoked assignments can still be archived.');

// Standard levels belong to a subject, are created with their module, and reuse a stable identity.
const levels=timetableFixture(),ls=timetableService(levels.repository,levels.program);
const lc=timetableCoordinator(levels.journal,async()=>({service:ls,user:{accountid:'ADMIN'}}));
const levelRequest=async(record,creating=true)=>{const view=await ls.read('manage-get');return {id:levels.program.id,operationId:crypto.randomUUID(),kind:'modules',creating,record,baseRowRevision:view.rowRevisions.modules[record.ProgramModuleID]||view.emptyRowRevision};};
const moduleRecord=(id,level='standard:Beginner',subject='PS-TAFSEER')=>({ProgramModuleID:id,ProgramSubjectID:subject,Name:id,LevelID:level,Active:true});
const atomic=await levelRequest(moduleRecord('MOD-STANDARD'));levels.failNext('after');
await assert.rejects(lc.run('manage-save',atomic,'token'),/Injected/);
const acknowledgement=await lc.run('manage-save',atomic,'token');assert(acknowledgement.replayed);assert.equal(acknowledgement.level.Name,'Beginner');
const stableLevelId=acknowledgement.record.LevelID;assert.equal(acknowledgement.level.LevelID,stableLevelId);
await lc.run('manage-save',await levelRequest(moduleRecord('MOD-REUSE')),'token');
let levelView=await ls.read('manage-get');assert.equal(levelView.rows.levels.length,1);assert(levelView.rows.modules.filter(m=>m.ProgramModuleID!=='MOD-DEMO').every(m=>m.LevelID===stableLevelId));
await lc.run('manage-save',await levelRequest(moduleRecord('MOD-OPTIONAL','')),'token');
for(const invalid of ['standard:Expert','standard:beginner','standard:'])await assert.rejects(lc.run('manage-save',await levelRequest(moduleRecord('MOD-INVALID',invalid)),'token'),/Choose Beginner/);
const snapshot=managementState(await levels.repository.load(),levels.program).snapshot;
snapshot.ProgramSubjects.push({ProgramSubjectID:'PS-ARABIC',SubjectID:'ARABIC',CourseID:levels.program.id,Active:true});
const scoped=applyManagementChange({snapshot},{kind:'modules',creating:true,record:moduleRecord('MOD-ARABIC','standard:Beginner','PS-ARABIC')},levels.shared,levels.program);
assert.notEqual(scoped.record.LevelID,stableLevelId);assert.equal(scoped.snapshot.ProgramLevels.length,2);
// Existing custom links stay intact; a new module cannot choose a custom level.
snapshot.ProgramLevels.push({LevelID:'LVL-LEGACY',ProgramSubjectID:'PS-TAFSEER',Name:'Foundation year',Active:true});
snapshot.ProgramModules[0].LevelID='LVL-LEGACY';
let legacy=applyManagementChange({snapshot},{kind:'modules',creating:false,record:{...snapshot.ProgramModules[0],Name:'Edited legacy module'}},levels.shared,levels.program);
assert.equal(legacy.record.LevelID,'LVL-LEGACY');assert.deepEqual(legacy.snapshot.ProgramLevels,snapshot.ProgramLevels);
assert.throws(()=>applyManagementChange({snapshot},{kind:'modules',creating:true,record:moduleRecord('MOD-CUSTOM','LVL-LEGACY')},levels.shared,levels.program),/standard level/);
legacy=applyManagementChange({snapshot},{kind:'modules',creating:false,record:{...snapshot.ProgramModules[0],LevelID:'standard:Intermediate'}},levels.shared,levels.program);
assert(legacy.snapshot.ProgramLevels.some(l=>l.LevelID==='LVL-LEGACY'),'Explicit replacement keeps historical level records');
const inactive=structuredClone(snapshot);inactive.ProgramLevels[0].Active=false;
const reactivated=applyManagementChange({snapshot:inactive},{kind:'modules',creating:true,record:moduleRecord('MOD-REACTIVATE')},levels.shared,levels.program);
assert.equal(reactivated.record.LevelID,stableLevelId);assert.equal(reactivated.snapshot.ProgramLevels[0].Active,true);
const duplicate=structuredClone(snapshot);duplicate.ProgramLevels.push({...duplicate.ProgramLevels[0],LevelID:'LVL-DUP'});
assert.throws(()=>applyManagementChange({snapshot:duplicate},{kind:'modules',creating:true,record:moduleRecord('MOD-DUP')},levels.shared,levels.program),/duplicate levels/);
// Optional level records must not strand subject archival when the Levels tab is removed.
const unused=structuredClone(scoped.snapshot);unused.ProgramModules=unused.ProgramModules.map(r=>({...r,Active:false}));
const archivedSubject=applyManagementChange({snapshot:unused},{kind:'subjects',creating:false,record:{...unused.ProgramSubjects[0],Active:false}},levels.shared,levels.program);
assert.equal(archivedSubject.record.Active,false);assert.deepEqual(archivedSubject.snapshot.ProgramLevels,unused.ProgramLevels);
assert.throws(()=>applyManagementChange({snapshot:scoped.snapshot},{kind:'subjects',creating:false,record:{...scoped.snapshot.ProgramSubjects[0],Active:false}},levels.shared,levels.program),/active dependent/);
console.log('Standard levels: atomic replay, reuse, optionality, subject scope, custom-link preservation, reactivation and subject archive passed.');
