import assert from 'node:assert/strict';
import { readWeeklyDraft,validateWeeklyTimetable,normalizeWeeklyDraft,programToday,WEEKLY_SCHEMA } from '../src/programs/weekly-timetable.js';
import { validateTimetable } from '../src/programs/timetable-model.js';
import { timetableService } from '../src/programs/timetable-service.js';
import { timetableCoordinator } from '../src/programs/timetable-coordination.js';
import { timetableFixture } from '../../scripts/program-timetable-fixtures.mjs';
const f=timetableFixture(),draft=readWeeklyDraft(f.draft).draft,clone=structuredClone;
const check=d=>validateWeeklyTimetable(d,f.catalog,f.program,'2026-09-29');
assert.equal(programToday('Asia/Riyadh',new Date('2026-09-28T22:00:00Z')),'2026-09-29');
assert.equal(programToday('America/Los_Angeles',new Date('2026-09-29T02:00:00Z')),'2026-09-28');
assert.throws(()=>normalizeWeeklyDraft(f.draft),/Refresh/);
assert.throws(()=>normalizeWeeklyDraft({...draft,startDate:'2026-09-29'}),/Dates/);
const shorthand=clone(f.draft);shorthand.rules[0].startTime='845';shorthand.rules[0].endTime='1015';
assert.equal(readWeeklyDraft(shorthand).draft.rules[0].startTime,'08:45');assert.equal(readWeeklyDraft(shorthand).draft.rules[0].endTime,'10:15');
assert.equal(check(draft).valid,true);assert.equal(check(draft).occurrences.length,2);
assert(!JSON.stringify(check(draft).snapshot).includes('endDate'));
let d=clone(draft);d.rules[0].teacherId='';assert(check(d).valid);assert.equal(check(d).occurrences[0].teacherName,'');
// Two unassigned teachers are not a teacher conflict; other overlaps remain enforced.
d.rules[0].classIds=['CLASS-1'];d.rules.push({...clone(d.rules[0]),id:'RULE-TWO',classIds:['CLASS-2']});
assert.deepEqual(check(d).conflicts[0].reasons,['Known learner membership overlap']);
f.catalog.enrollments[1].endDate='2026-09-28';assert(check(d).valid);
f.catalog.enrollments[1].endDate='2026-09-29';assert(check(d).valid,'Tuesday-only membership does not overlap the Mon/Wed pattern');
f.catalog.enrollments[1].endDate='2026-09-30';assert(!check(d).valid);f.catalog.enrollments[1].endDate='';
d.rules[1].weekdays=[2];assert(check(d).valid);d.rules[1].weekdays=[1];d.rules[1].classIds=['CLASS-1'];assert(check(d).conflicts[0].reasons.includes('Class overlap'));
for(const [start,end] of [['24:00','25:00'],['08:65','10:15'],['10:15','08:45']]){d=clone(draft);Object.assign(d.rules[0],{startTime:start,endTime:end});assert(!check(d).valid);}
d=clone(draft);d.rules[0].teacherId='missing';assert(!check(d).valid);d.rules[0].teacherId='TEACHER-1';f.catalog.teachers[0].active=false;assert(!check(d).valid);f.catalog.teachers[0].active=true;
let clock='2026-09-29T09:00:00Z';
const service=timetableService(f.repository,f.program,()=>new Date(clock));
const coordinator=timetableCoordinator(f.journal,async()=>({service,user:{accountid:'ADMIN'}}));
async function input(extra={}){return {id:f.program.id,operationId:crypto.randomUUID(),revision:(await service.read('get')).revision,draft:clone(draft),...extra};}
const p1=await coordinator.run('publish',await input(),'token');assert.equal(p1.effectiveFrom,'2026-09-29');
const snapshot1=f.tables.ProgramTimetablePublications[0].SnapshotJSON;
const p2=await coordinator.run('publish',await input({effectiveFrom:'2026-10-05'}),'token');
assert.equal(p2.currentPublicationId,p1.publicationId);assert.equal(p2.publications[1].status,'SCHEDULED');
assert.equal((await service.read('published')).publication.id,p1.publicationId);
assert.equal((await service.read('published',{date:'2026-10-04'})).publication.id,p1.publicationId);
assert.equal((await service.read('published',{date:'2026-10-05'})).publication.id,p2.publicationId);
assert.equal((await service.read('published',{date:'2099-12-31'})).publication.id,p2.publicationId,'No date window or 366-day cap');
clock='2026-10-04T22:00:00Z';assert.equal((await service.read('get')).currentPublicationId,p2.publicationId,'Activates at Program midnight without writes');
const p3=await coordinator.run('publish',await input({effectiveFrom:'2026-11-01'}),'token');
const p4=await coordinator.run('publish',await input({effectiveFrom:'2026-10-12'}),'token');
assert.equal((await service.read('published',{date:'2026-11-02'})).publication.id,p4.publicationId,'An older scheduled version must never revive after a newer one');
assert.equal((await service.read('history')).publications.find(p=>p.id===p3.publicationId).status,'SUPERSEDED');
const p5=await coordinator.run('publish',await input({effectiveFrom:'2026-10-12'}),'token');
assert.equal((await service.read('published',{date:'2026-10-12'})).publication.id,p5.publicationId,'Latest version wins same effective date');
const count=f.tables.ProgramTimetablePublications.length;
await assert.rejects(coordinator.run('publish',await input({effectiveFrom:'2026-09-29'}),'token'),/backdated/);
assert.equal(f.tables.ProgramTimetablePublications.length,count);assert.equal(await f.journal.get(),null);
d=clone(draft);d.rules[0].startTime='12:00';await coordinator.run('save',await input({draft:d}),'token');
assert.equal((await service.read('published')).publication.occurrences[0].startTime,'13:00');
assert.equal(f.tables.ProgramTimetablePublications[0].SnapshotJSON,snapshot1);
// Unknown acknowledgement retains both effective date and identity across midnight.
const lost=await input({effectiveFrom:'2026-10-06'});f.failNext('after');await assert.rejects(coordinator.run('publish',lost,'token'));
clock='2026-10-07T09:00:00Z';const replay=await coordinator.run('publish',lost,'token');assert(replay.replayed);assert.equal(replay.effectiveFrom,'2026-10-06');
assert.equal(f.tables.ProgramTimetablePublications.filter(p=>p.OperationID===lost.operationId).length,1);
// Legacy drafts and publications remain readable and immutable.
const old=timetableFixture(),oldSnapshot=validateTimetable(old.draft,old.catalog,old.program).snapshot;
old.draft.rules.push({...clone(old.draft.rules[0]),id:'RULE-ONEOFF',kind:'EXPLICIT',startDate:'2026-09-22',endDate:'2026-09-22'});
old.draft.exceptions=[{id:'EX-CANCEL',ruleId:'RULE-DEMO',originalDate:'2026-09-21',action:'CANCEL'}];
old.tables.ProgramTimetableState.push({_rowNumber:2,CourseID:old.program.id,SchemaVersion:'105.2',Sequence:1,Revision:'old',DraftJSON:JSON.stringify(old.draft),CurrentPublicationID:'PUB-OLD'});
old.tables.ProgramTimetablePublications.push({_rowNumber:2,PublicationID:'PUB-OLD',CourseID:old.program.id,VersionNo:1,PublishedDate:'2026-09-20T00:00:00Z',SnapshotJSON:JSON.stringify(oldSnapshot)});
const legacyBytes=JSON.stringify(old.tables),oldService=timetableService(old.repository,old.program,()=>new Date('2026-09-29T09:00:00Z'));
const oldCoordinator=timetableCoordinator(old.journal,async()=>({service:oldService,user:{accountid:'ADMIN'}}));
const current=await oldService.read('get');assert(current.conversion.required);assert.equal(current.conversion.oneOffCount,1);assert.equal(current.conversion.exceptionCount,1);assert.equal(current.draft.rules.length,1);
assert.equal((await oldService.read('history')).publications[0].occurrences.length,4);assert.equal(JSON.stringify(old.tables),legacyBytes);
const migration={id:old.program.id,operationId:crypto.randomUUID(),revision:current.revision,draft:current.draft};
await assert.rejects(oldCoordinator.run('save',migration,'token'),/Use weekly lessons/);
await oldCoordinator.run('save',{...migration,convertLegacy:true},'token');
assert.equal(old.tables.ProgramTimetableState[0].DraftJSON,JSON.stringify(old.draft));
assert.equal(old.tables.ProgramTimetableState[1].SchemaVersion,WEEKLY_SCHEMA);
assert.equal((await oldService.read('published',{date:'2026-10-05'})).publication,null,'Expired historical dated publication does not become ongoing');
assert.deepEqual((await oldService.read('history')).publications[0].snapshot,oldSnapshot);
// A cached dated editor can still save unfinished rows before refreshing to the new UI.
const cached=timetableFixture(),cachedService=timetableService(cached.repository,cached.program,()=>new Date('2026-09-29T09:00:00Z'));
const cachedCoordinator=timetableCoordinator(cached.journal,async()=>({service:cachedService,user:{accountid:'ADMIN'}}));
cached.draft.rules[0].startTime='845';
const cachedInput={id:cached.program.id,operationId:crypto.randomUUID(),revision:'',draft:cached.draft};
const cachedSave=await cachedCoordinator.run('save',cachedInput,'token');assert(cachedSave.upgradeRequired);
assert((await cachedCoordinator.run('save',cachedInput,'token')).replayed);
assert.equal((await cachedService.read('get')).draft.rules[0].startTime,'08:45');
await assert.rejects(cachedCoordinator.run('publish',{...cachedInput,operationId:crypto.randomUUID(),revision:cachedSave.revision},'token'),/Refresh/);
assert.equal(cached.tables.ProgramTimetablePublications.length,0);
const unset=timetableFixture();unset.program.timezone='';assert.equal((await timetableService(unset.repository,unset.program).read('get')).effectiveTimezone,'UTC');
console.log('Weekly timetable: optional teachers, recurring conflicts, no date cap, future activation, supersession, immutable history, legacy conversion and stable retries passed.');
