import assert from 'node:assert/strict';
import { timetableFixture } from '../../scripts/program-timetable-fixtures.mjs';
import { timetableService } from '../src/programs/timetable-service.js';
import { timetableCoordinator } from '../src/programs/timetable-coordination.js';
import { managementState } from '../src/programs/management-model.js';
const f=timetableFixture(),service=timetableService(f.repository,f.program);
let authorized=true;
const coordinator=timetableCoordinator(f.journal,async()=>{if(!authorized)throw new Error('revoked');return {service,user:{accountid:'ADMIN'}};});
const request=async(record,creating=true)=>{const view=await service.read('manage-get');return {id:f.program.id,kind:'progress',record,creating,revision:view.revision,referenceRevision:view.referenceRevision,operationId:crypto.randomUUID()};};
const record=(ClassID,Status,ProgressID=`MP-${ClassID}`)=>({ProgressID,ProgramModuleID:'MOD-DEMO',ClassID,Status});
assert.deepEqual((await service.read('manage-get')).rows.progress,[]);
const before=structuredClone(managementState(await f.repository.load(),f.program).snapshot);
await coordinator.run('manage-save',await request(record('CLASS-1','COMPLETED')),'token');
await coordinator.run('manage-save',await request(record('CLASS-2','ACTIVE')),'token');
let view=await service.read('manage-get');assert.equal(view.rows.progress.length,2);
assert.equal(view.rows.progress.find(r=>r.ClassID==='CLASS-1').Status,'COMPLETED');assert.equal(view.rows.progress.find(r=>r.ClassID==='CLASS-2').Status,'ACTIVE');
assert.equal((await service.read('get')).catalog.modules[0].active,true);
for(const invalid of [record('CLASS-1','COMPLETED','MP-DUP'),record('OTHER','ACTIVE'),{...record('CLASS-1','ACTIVE','MP-MISSING'),ProgramModuleID:'OTHER'},record('CLASS-1','complete','MP-BAD')])await assert.rejects(coordinator.run('manage-save',await request(invalid),'token'));
await assert.rejects(coordinator.run('manage-save',await request({...record('CLASS-1','ACTIVE'),ClassID:'CLASS-2'},false),'token'),/cannot move/);
const reopen=await request(record('CLASS-1','INACTIVE'),false);f.failNext('after');await assert.rejects(coordinator.run('manage-save',reopen,'token'),/Injected/);
assert((await coordinator.run('manage-save',reopen,'token')).replayed);
const retry=await request(record('CLASS-1','COMPLETED'),false);f.failNext('before');await assert.rejects(coordinator.run('manage-save',retry,'token'),/Injected/);
authorized=false;await assert.rejects(coordinator.run('recover',{id:f.program.id},'token'),/revoked/);authorized=true;
await coordinator.run('recover',{id:f.program.id},'token');assert((await coordinator.run('manage-save',retry,'token')).replayed);
const stale=await request(record('CLASS-1','ACTIVE'),false);await coordinator.run('manage-save',await request(record('CLASS-2','INACTIVE'),false),'token');await assert.rejects(coordinator.run('manage-save',stale,'token'),/changed/);
const after=managementState(await f.repository.load(),f.program).snapshot;
for(const key of Object.keys(before))if(key!=='ProgramModuleProgress')assert.deepEqual(after[key],before[key]);
const bad=structuredClone(await f.repository.load());const latest=bad.tables.ProgramManagementState.at(-1);let snap=JSON.parse(latest.SnapshotJSON);snap.ProgramModuleProgress[0].CourseID='FOREIGN';latest.SnapshotJSON=JSON.stringify(snap);assert.throws(()=>managementState(bad,f.program),/another Program/);
snap.ProgramModuleProgress[0].CourseID=f.program.id;snap.ProgramModuleProgress.push({...snap.ProgramModuleProgress[0],ProgressID:'MP-DUP'});latest.SnapshotJSON=JSON.stringify(snap);assert.throws(()=>managementState(bad,f.program),/duplicate/);
// Older snapshots are upgraded in memory; other edits must retain progress.
const historical=structuredClone(await f.repository.load());const older=historical.tables.ProgramManagementState.at(-1);const oldSnapshot=JSON.parse(older.SnapshotJSON);delete oldSnapshot.ProgramModuleProgress;older.SnapshotJSON=JSON.stringify(oldSnapshot);assert.deepEqual(managementState(historical,f.program).snapshot.ProgramModuleProgress,[]);
view=await service.read('manage-get');await coordinator.run('manage-save',{id:f.program.id,kind:'classes',record:{...view.rows.classes[0],Name:'Renamed class'},creating:false,revision:view.revision,referenceRevision:view.referenceRevision,operationId:crypto.randomUUID()},'token');assert.deepEqual((await service.read('manage-get')).rows.progress,after.ProgramModuleProgress);
f.program.status='ARCHIVED';await assert.rejects(coordinator.run('manage-save',await request(record('CLASS-1','ACTIVE'),false),'token'),/Archived/);
console.log('Module progress: per-class completion, duplicate/reference validation, retry/recovery, authority, stale edits, legacy snapshots and preserved curriculum passed.');
