import assert from 'node:assert/strict';
import { timetableFixture } from '../../scripts/program-timetable-fixtures.mjs';
import { timetableService } from '../src/programs/timetable-service.js';
import { timetableCoordinator } from '../src/programs/timetable-coordination.js';
import { applyManagementChange, managementState } from '../src/programs/management-model.js';
const f=timetableFixture(),service=timetableService(f.repository,f.program);
let authorized=true;
const coordinator=timetableCoordinator(f.journal,async()=>{if(!authorized)throw new Error('revoked');return {service,user:{accountid:'ADMIN'}};});
let view=await service.read('manage-get');
const input=(record,kind='classes',creating=true)=>({id:f.program.id,operationId:crypto.randomUUID(),revision:view.revision,referenceRevision:view.referenceRevision,kind,record,creating});
await coordinator.run('manage-save',input({ClassID:'CLS-1',Name:'Evening',Active:true}),'token');
const firstPlan=structuredClone(f.plans[0]);
view=await service.read('manage-get');
const requests=[input({ClassID:'CLS-2',Name:'Morning',Active:true}),input({ClassID:'CLS-3',Name:'Weekend',Active:true})];
const outcomes=await Promise.allSettled(requests.map(r=>coordinator.run('manage-save',r,'token')));
assert.equal(outcomes.filter(r=>r.status==='fulfilled').length,1);
view=await service.read('manage-get');assert.equal(view.rows.classes.length,4);
await f.repository.apply(firstPlan);assert.equal((await service.read('manage-get')).revision,view.revision);
const uncertain=input({ClassID:'CLS-RETRY',Name:'Retry',Active:true});f.failNext('before');
await assert.rejects(coordinator.run('manage-save',uncertain,'token'),/Injected/);
authorized=false;await assert.rejects(coordinator.run('recover',{id:f.program.id},'token'),/revoked/);
authorized=true;await coordinator.run('recover',{id:f.program.id},'token');
assert((await coordinator.run('manage-save',uncertain,'token')).replayed);
assert.equal((await service.read('manage-get')).rows.classes.filter(r=>r.ClassID==='CLS-RETRY').length,1);
view=await service.read('manage-get');
await assert.rejects(coordinator.run('manage-save',input({ProgramSubjectID:'PS-ARABIC',SubjectID:'ARABIC',Active:'true'},'subjects'),'token'),/Active or Archived/);
await coordinator.run('manage-save',input({ProgramSubjectID:'PS-ARABIC',SubjectID:'ARABIC',Active:true},'subjects'),'token');
view=await service.read('manage-get');
await coordinator.run('manage-save',input({LevelID:'LVL-ARABIC',ProgramSubjectID:'PS-ARABIC',Name:'L1',Active:true},'levels'),'token');
view=await service.read('manage-get');
await assert.rejects(coordinator.run('manage-save',input({ProgramModuleID:'MOD-WRONG',ProgramSubjectID:'PS-TAFSEER',LevelID:'LVL-ARABIC',Name:'Wrong scope',Active:true},'modules'),'token'),/level must belong/);
await assert.rejects(coordinator.run('manage-save',input({ProgramSubjectID:'PS-DUP',SubjectID:'ARABIC',Active:true},'subjects'),'token'),/already linked/);
f.program.status='ARCHIVED';await assert.rejects(coordinator.run('manage-save',input({ClassID:'CLS-BLOCK',Name:'Blocked',Active:true}),'token'),/Archived/);f.program.status='DRAFT';
const state=managementState(await f.repository.load(),f.program),refs=await f.repository.managementReferences();
assert.throws(()=>applyManagementChange(state,{kind:'classes',creating:true,record:{ClassID:'CLS-X',Name:'Evening',Active:true}},refs,f.program),/name already exists/);
const foreign=structuredClone(await f.repository.load());foreign.tables.ProgramManagementState[0].CourseID='OTHER';assert.throws(()=>managementState(foreign,f.program),/history needs repair/);
// Bulk imports append missing links atomically and never replace archived/dependent rows.
const batch=timetableFixture(),bs=timetableService(batch.repository,batch.program);
const bc=timetableCoordinator(batch.journal,async()=>({service:bs,user:{accountid:'ADMIN'}}));
batch.shared.subjects.push({SubjectID:'FIQH',SubjectName:'Fiqh',Active:true},{SubjectID:'HADITH',SubjectName:'Hadith',Active:true},{SubjectID:'OLD',SubjectName:'Archived',Active:false},{SubjectID:'LEGACY',SubjectName:'Old course',Active:true,Legacy:true});
const original=structuredClone(managementState(await batch.repository.load(),batch.program).snapshot);
const bulk=async ids=>{const v=await bs.read('manage-get');return {id:batch.program.id,operationId:crypto.randomUUID(),revision:v.revision,referenceRevision:v.referenceRevision,kind:'subject-import',record:{subjectIds:ids}};};
for(const ids of [[],['MISSING'],['OLD'],['LEGACY'],['FIQH','MISSING'],Array(251).fill('FIQH')])await assert.rejects(bc.run('manage-save',await bulk(ids),'token'));
assert.deepEqual(managementState(await batch.repository.load(),batch.program).snapshot,original);
const one=await bulk(['FIQH']);
batch.failNext('after');await assert.rejects(bc.run('manage-save',one,'token'),/Injected/);
const replay=await bc.run('manage-save',one,'token');assert(replay.replayed);assert.equal(replay.record.added,1);
const multi=await bulk(['FIQH','ARABIC','ARABIC','HADITH']);
batch.failNext('before');await assert.rejects(bc.run('manage-save',multi,'token'),/Injected/);
assert((await bc.run('recover',{id:batch.program.id},'token')).recovered);
assert.deepEqual((await bc.run('manage-save',multi,'token')).record,{added:2,alreadyLinked:1,archived:0});
assert.deepEqual(await bc.run('recover',{id:batch.program.id},'token'),{recovered:false});
const saved=(await bs.read('manage-get')).rows.subjects;
assert.equal(saved.length,4);assert.equal(new Set(saved.map(r=>r.SubjectID)).size,4);
assert.deepEqual((await bc.run('manage-save',await bulk(['FIQH','ARABIC','HADITH']),'token')).record,{added:0,alreadyLinked:3,archived:0});
const after=managementState(await batch.repository.load(),batch.program).snapshot;
for(const key of Object.keys(original))if(key!=='ProgramSubjects')assert.deepEqual(after[key],original[key]);
const stale=await bulk(['FIQH']);await bc.run('manage-save',await bulk(['HADITH']),'token');
await assert.rejects(bc.run('manage-save',stale,'token'),/changed/);
const archived=structuredClone(after);archived.ProgramSubjects.find(r=>r.SubjectID==='FIQH').Active=false;
const unchanged=applyManagementChange({snapshot:archived},{kind:'subject-import',record:{subjectIds:['FIQH']}},batch.shared,batch.program);
assert.deepEqual(unchanged.record,{added:0,alreadyLinked:1,archived:1});assert.deepEqual(unchanged.snapshot,archived);
console.log('Program import: single/multiple selection, canonical deduplication, archived preservation, atomic failure, stale revisions and replay/recovery passed.');
console.log('Program management: shared subjects, level scope, duplicates, archive guards, authority, concurrent edits, recovery and late-write preservation passed.');
