import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

const adminHtml = readFileSync(new URL("../../admin/index.html", import.meta.url), "utf8");
const studentHtml = readFileSync(new URL("../../student/index.html", import.meta.url), "utf8");
const manageJs = readFileSync(new URL("../../js/m4l-manage-resources.js", import.meta.url), "utf8");
const resourcesJs = readFileSync(new URL("../../js/m4l-resources.js", import.meta.url), "utf8");
const styles = readFileSync(new URL("../../styles.css", import.meta.url), "utf8");
const css = readFileSync(new URL("../../css/m4l-21-manage-resources.css", import.meta.url), "utf8");

assert.match(adminHtml, /id="open-manage-resources-btn"/);
assert.match(adminHtml, /id="manage-resources-screen"/);
assert.match(adminHtml, /id="manage-resources-content"/);
assert.match(adminHtml, /m4l-manage-resources\.js\?v=102\.6\.1/);
assert.match(adminHtml, /m4l-resources\.js\?v=105\.4\.2\.25/);
assert.match(studentHtml, /m4l-resources\.js\?v=105\.4\.2\.25/);
assert.match(manageJs, /\["ADMIN", "SENIOR", "TEACHER"\]\.includes\(getCurrentRole\(\)\)/);
assert.match(manageJs, /function canModifyResources\(\)/);
assert.match(manageJs, /Only ADMIN accounts can modify existing resources/);
assert.match(manageJs, /\/api\/admin\/drive\/browse/);
assert.match(manageJs, /\/api\/admin\/resources\/create/);
assert.match(manageJs, /\/api\/admin\/resources\/manage-list/);
assert.match(manageJs, /\/api\/admin\/resources\/update/);
assert.match(manageJs, /Browse Shared Google Folder/);
assert.match(manageJs, /Add Another Resource/);
assert.match(manageJs, /data-resource-type=/);
assert.match(manageJs, /data-resource-id=/);
assert.doesNotMatch(manageJs, /id="manage-resource-task"/);
assert.doesNotMatch(manageJs, /Task — optional/);
assert.doesNotMatch(manageJs, /<label class="student-admin-label">Format<\/label>/);
assert.doesNotMatch(manageJs, /taskId:\s*stateModel\.form\.taskId/);
assert.match(resourcesJs, /\/api\/library\/drive\/access/);
assert.match(resourcesJs, /resolveLibraryResourceLink/);
assert.match(resourcesJs, /invalidateLibraryResourceCache/);
assert.match(styles, /m4l-21-manage-resources\.css\?v=100\.4\.2/);
assert.match(css, /\.manage-drive-list\s*\{[\s\S]*max-height:\s*min\(58vh, 520px\)[\s\S]*overflow-y:\s*auto/);
assert.match(css, /manage-drive-breadcrumbs/);
assert.match(css, /managed-resource-row/);

console.log("Resource management UI integration tests passed.");
