import assert from "node:assert/strict";
import { existsSync, readFileSync } from "node:fs";

const adminHtml = readFileSync(new URL("../../admin/index.html", import.meta.url), "utf8");
const builderJs = readFileSync(new URL("../../js/m4l-timetable-builder.js", import.meta.url), "utf8");
const builderCss = readFileSync(new URL("../../css/m4l-22-timetable-builder.css", import.meta.url), "utf8");
const styles = readFileSync(new URL("../../styles.css", import.meta.url), "utf8");
const shellJs = readFileSync(new URL("../../js/m4l-shell.js", import.meta.url), "utf8");
const authJs = readFileSync(new URL("../../js/m4l-auth.js", import.meta.url), "utf8");

assert.match(adminHtml, /id="open-timetable-builder-btn"/);
assert.match(adminHtml, /data-admin-menu-admin-only/);
assert.match(adminHtml, /onclick="showTimetableBuilder\(\)"/);
assert.match(adminHtml, /id="timetable-builder-screen"/);
assert.match(adminHtml, /data-ttb-tab="timetable"/);
assert.match(adminHtml, /data-ttb-tab="courses"/);
assert.match(adminHtml, /data-ttb-tab="subjects"/);
assert.match(adminHtml, /data-ttb-tab="modules"/);
assert.match(adminHtml, /data-ttb-tab="tasks"/);
assert.match(adminHtml, /id="timetable-session-dialog"/);
assert.match(adminHtml, /id="ttb-session-days"/);
assert.match(adminHtml, /id="ttb-session-slot"/);
assert.match(adminHtml, /id="ttb-session-subject"/);
assert.match(adminHtml, /id="ttb-session-module"/);
assert.match(adminHtml, /id="ttb-session-groups"/);
assert.match(adminHtml, /id="ttb-session-group-assignments"/);
assert.match(adminHtml, /id="ttb-delete-session"/);
assert.match(adminHtml, /id="ttb-restore-session"/);
assert.match(adminHtml, /id="timetable-builder-publish"/);
assert.match(adminHtml, /id="ttb-save-session"/);
assert.match(adminHtml, /id="timetable-session-message"/);
assert.match(adminHtml, /id="timetable-bulk-session-dialog"/);
assert.match(adminHtml, /id="ttb-bulk-session-count"/);
assert.match(adminHtml, /id="ttb-bulk-apply-subject-module"[^>]+data-ttb-bulk-apply/);
assert.match(adminHtml, /id="ttb-bulk-apply-teacher"[^>]+data-ttb-bulk-apply/);
assert.match(adminHtml, /id="ttb-bulk-apply-zoom"[^>]+data-ttb-bulk-apply/);
assert.match(adminHtml, /id="ttb-bulk-subject"/);
assert.match(adminHtml, /id="ttb-bulk-module"/);
assert.match(adminHtml, /id="ttb-bulk-teacher"/);
assert.match(adminHtml, /id="ttb-bulk-zoom"/);
assert.match(adminHtml, /data-ttb-action="save-bulk-sessions"/);
assert.match(adminHtml, /id="timetable-builder-integration"/);
assert.match(adminHtml, /id="timetable-integration-dialog"/);
assert.match(adminHtml, /id="ttb-integration-confirmation"/);
assert.match(adminHtml, /data-ttb-action="save-integration-source"/);
assert.match(adminHtml, /Leave blank to use the program-default Zoom/);
assert.match(adminHtml, /Program Timetables/);
assert.match(adminHtml, /Programs &amp; Times/);
assert.match(adminHtml, /m4l-timetable-builder\.js\?v=106\.9/);
assert.match(adminHtml, /m4l-auth\.js\?v=102\.9\.1/);
assert.match(adminHtml, /m4l-timetable\.js\?v=102\.9\.1/);

assert.match(builderJs, /getTimetableBuilderRole\(\) !== "ADMIN"/);
assert.match(builderJs, /\["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"\]/);
assert.match(builderJs, /\/api\/admin\/timetable-builder\/get/);
assert.match(builderJs, /\/api\/admin\/timetable-builder\/course\/save/);
assert.match(builderJs, /\/api\/admin\/timetable-builder\/time-slot\/save/);
assert.match(builderJs, /\/api\/admin\/timetable-builder\/session\/save/);
assert.match(builderJs, /\/api\/admin\/timetable-builder\/session\/bulk-update/);
assert.match(builderJs, /\/api\/admin\/timetable-builder\/session\/delete/);
assert.match(builderJs, /\/api\/admin\/timetable-builder\/session\/restore/);
assert.match(builderJs, /\/api\/admin\/timetable-builder\/publish/);
assert.match(builderJs, /\/api\/admin\/timetable-builder\/integration\/preview/);
assert.match(builderJs, /\/api\/admin\/timetable-builder\/integration\/source\/save/);
assert.match(builderJs, /\/api\/admin\/subjects\/create/);
assert.match(builderJs, /\/api\/admin\/subjects\/update/);
assert.match(builderJs, /\/api\/admin\/modules\/create/);
assert.match(builderJs, /\/api\/admin\/modules\/update/);
assert.match(builderJs, /\/api\/admin\/tasks\/create/);
assert.match(builderJs, /\/api\/admin\/tasks\/update/);
assert.match(builderJs, /daysofweek/);
assert.match(builderJs, /groupassignments/);
assert.match(builderJs, /renderTimetableSessionGroupAssignments/);
assert.match(builderJs, /collectTimetableSessionGroupAssignments/);
assert.match(builderJs, /ttb-session-group-teacher/);
assert.match(builderJs, /ttb-session-group-zoom/);
assert.match(builderJs, /Development draft/);
assert.match(builderJs, /immutable snapshot/);
assert.doesNotMatch(builderJs, /renderTimetableSessionLessons/);
assert.match(builderJs, /input\[name='ttb-session-day'\]/);
assert.match(builderJs, /input\[name='ttb-session-group'\]/);
assert.match(builderJs, /enforceTimetableBuilderGroupSelection/);
assert.match(builderJs, /result\.conflicts/);
assert.match(builderJs, /09:00–10:30|padStart\(2, "0"\)/);
assert.match(builderJs, /lang="en-GB" step="60"/);
assert.match(builderJs, /TeacherAssign remains the live timetable source/);
assert.match(builderJs, /requiredConfirmation/);
assert.match(builderJs, /Activate Published Timetable/);
assert.match(builderJs, /Return to TeacherAssign/);
assert.match(builderJs, /clearTimetableCache/);
assert.match(builderJs, /result\.publicationBecomesLive/);
assert.match(builderJs, /startTimetableBulkSelection/);
assert.match(builderJs, /toggleTimetableSessionSelection/);
assert.match(builderJs, /applysubjectmodule/);
assert.match(builderJs, /applyteacher/);
assert.match(builderJs, /applyzoom/);
assert.match(builderJs, /applyTimetableSessionUpdates/);
assert.match(builderJs, /result\.changed !== false/);
assert.doesNotMatch(builderJs, /apiPost\(\s*"\/api\/admin\/tasks\/list"/);

assert.match(styles, /m4l-22-timetable-builder\.css\?v=102\.9\.1/);
assert.match(builderCss, /\.timetable-builder-tabs button\s*\{[^}]*width:\s*auto/s);
assert.match(builderCss, /\.timetable-builder-status-band > button\s*\{[^}]*width:\s*auto/s);
assert.match(builderCss, /\.timetable-builder-course-bar > button\s*\{[^}]*width:\s*auto/s);
assert.match(builderCss, /\.timetable-builder-grid-title-actions\s*\{[^}]*flex-wrap:\s*wrap/s);
assert.match(builderCss, /@media \(max-width: 640px\)[\s\S]*\.timetable-builder-status-band > button\s*\{[^}]*flex:\s*1 1 140px/);
assert.match(builderCss, /grid-template-columns:\s*132px repeat\(var\(--ttb-day-count\), minmax\(152px, 1fr\)\)/);
assert.match(builderCss, /min-width:\s*1240px/);
assert.match(builderCss, /grid-template-columns:\s*minmax\(290px, 360px\) minmax\(520px, 1fr\)/);
assert.match(builderCss, /\.timetable-builder-choice-grid/);
assert.match(builderCss, /\.timetable-session-group-assignment-grid/);
assert.match(builderCss, /\.timetable-session-message\.is-error/);
assert.match(builderCss, /\.ttb-session-card\.is-selected/);
assert.match(builderCss, /\.ttb-session-select-indicator/);
assert.match(builderCss, /\.timetable-builder-bulk-fieldset/);
assert.match(builderCss, /\.timetable-integration-dialog/);
assert.match(builderCss, /\.timetable-integration-checks/);
assert.match(builderCss, /\.timetable-integration-confirm-field/);
assert.match(shellJs, /id === "timetable-builder-screen"/);
assert.match(authJs, /NETWORK_TEMPORARILY_UNAVAILABLE/);
assert.match(authJs, /Your session remains active/);
assert.match(authJs, /response\.status === 429 \|\| response\.status >= 500/);

assert.equal(existsSync(new URL("../../icons/timetable.svg", import.meta.url)), true);

console.log("Timetable Builder UI integration tests passed.");
