import assert from 'node:assert/strict';
import { userProfilesFixture } from '../../scripts/user-profiles-fixtures.mjs';
import { profileService } from '../src/profiles/service.js';
import { parseRoles } from '../src/profiles/academy-access.js';
import { timetableCoordinator } from '../src/programs/timetable-coordination.js';
const f=userProfilesFixture(),service=profileService(f.repository),coordinator=timetableCoordinator(f.journal,async()=>({service,user:f.authorize()}));
let view=await service.read('get');
const request=async(accountId,scopeType,scopeId,roles,extra={})=>{view=await service.read('get');const record=view.accounts.find(a=>a.accountId===accountId)?.assignments.find(a=>a.scopeType===scopeType&&a.scopeId===scopeId);return {operationId:crypto.randomUUID(),mode:'matrix-roles',accountId,scopeType,scopeId,roles,baseRevision:record?.revision,scopeRevision:view.scopes.find(s=>s.type===scopeType&&s.id===scopeId)?.revision,...extra};};
const save=input=>coordinator.run('save',input,'token');
const profile=async(accountId,extra={})=>{view=await service.read('get');const current=view.accounts.find(a=>a.accountId===accountId);return {operationId:crypto.randomUUID(),mode:'profile',accountId,creating:!current,displayName:current?.displayName||'New person',active:true,baseRevision:current?.revision||view.emptyRevision,...extra};};
const policy=async(scopeId,accessModel)=>{view=await service.read('get');const scope=view.scopes.find(s=>s.id===scopeId);return {operationId:crypto.randomUUID(),mode:'matrix-policy',scopeType:scope.type,scopeId,accessModel,baseRevision:scope.revision,policyConfirmed:true};};
assert.equal(view.accounts.length,2);assert(!JSON.stringify(view).includes('private'));assert(!JSON.stringify(view).includes('UniqueID'));assert.equal(view.prepared,false);
const legacy=structuredClone([f.tables.UserCourseAccess,f.tables.GlobalSubjectAccessMatrix,f.tables.GlobalSubjectAccessPolicy,f.tables.AcademySubjectRoles]);
await assert.rejects(save(await profile('PERSON')),/Set up/);
const prepare={mode:'matrix-prepare',operationId:crypto.randomUUID()};await save(prepare);assert((await save(prepare)).replayed);
view=await service.read('get');assert.equal(view.prepared,true);assert.equal(view.reviewCount,1);assert.equal(view.scopes.find(s=>s.id==='REBOOT').reviewStatus,'REQUIRED');
assert.equal(view.accounts[0].assignments.find(g=>g.scopeId==='PAID').reviewStatus,'REQUIRED');
assert.deepEqual(view.accounts[1].assignments.find(g=>g.scopeId==='REBOOT').roles,['TEACHER']);
assert.deepEqual(view.accounts[0].assignments.find(g=>g.scopeId==='PAID').roles,['STUDENT']);
const rawAccount=structuredClone(f.tables.UserAccounts[1]);
await save(await profile('PERSON',{displayName:'Updated profile',PlatformRole:'GLOBAL_ADMIN',PINHash:'replace-me'}));
for(const field of ['UniqueID','PINSetup','PINHash','PlatformRole'])assert.equal(f.tables.UserAccounts[1][field],rawAccount[field]);
await assert.rejects(save(await profile('OWNER',{active:false})),/own account/);
const stale=await profile('PERSON');await save(await profile('PERSON',{displayName:'Another administrator edit'}));
await assert.rejects(save(stale),e=>e.code==='ROW_CHANGED'&&!JSON.stringify(e.currentRecord).includes('private'));
await save(await request('PERSON','PROGRAM','PRG-DEMO',['STUDENT','TEACHER']));
await assert.rejects(save(await request('PERSON','PROGRAM','PRG-DEMO',['GLOBAL_ADMIN'])),/valid roles/);
await assert.rejects(save(await request('PERSON','PROGRAM','MISSING',['TEACHER'])),/Update the matrix/);
await assert.rejects(save(await request('PERSON','SUBJECT','FREE',['TEACHER'],{mode:'roles'})),/new academy matrix/);
assert.throws(()=>parseRoles('TRUE'),/invalid roles/);assert.throws(()=>parseRoles('USER|TEACHER'),/invalid roles/);
await save(await request('PERSON','SUBJECT','FREE',['STUDENT']));
await save(await request('PERSON','SUBJECT','PAID',['TEACHER','ADMIN']));
view=await service.read('get');assert.equal(view.accounts[1].assignments.find(g=>g.scopeId==='PAID').accessAllowed,true,'Staff may access paid scope without Student');
await save(await request('PERSON','SUBJECT','PAID',[]));
view=await service.read('get');assert.equal(view.accounts[1].assignments.find(g=>g.scopeId==='PAID').accessAllowed,false);
const outdated=await request('PERSON','SUBJECT','PAID',['TEACHER']);
await assert.rejects(save({...await policy('PAID','FREE'),policyConfirmed:false}),/entire program/);
await save(await policy('PAID','FREE'));await assert.rejects(save(outdated),/Free\/Paid setting changed/);
view=await service.read('get');assert.equal(view.accounts[1].assignments.find(g=>g.scopeId==='PAID').accessAllowed,true,'Active default users may access free scopes');
await save(await profile('PERSON',{active:false}));
view=await service.read('get');assert.equal(view.accounts[1].assignments.find(g=>g.scopeId==='PAID').accessAllowed,false);
await assert.rejects(save(await request('PERSON','PROGRAM','PRG-DEMO',['STUDENT','TEACHER','ADMIN'])),/Reactivate the account/);
await save(await profile('PERSON',{active:true}));
await save(await request('PERSON','PROGRAM','REBOOT',['TEACHER','ADMIN']));
assert.deepEqual([f.tables.UserCourseAccess,f.tables.GlobalSubjectAccessMatrix,f.tables.GlobalSubjectAccessPolicy,f.tables.AcademySubjectRoles],legacy,'Setup must not change legacy access or linked identities');
const matrixBefore=structuredClone(f.tables.AcademyAccessMatrix);await save({mode:'matrix-prepare',operationId:crypto.randomUUID()});assert.deepEqual(f.tables.AcademyAccessMatrix,matrixBefore,'Re-import never replaces reviewed roles');
f.tables.GlobalSubjectList.push({SubjectID:'NEW',SubjectName:'New subject',Active:true});f.tables.GlobalSubjectAccessPolicy.push({SubjectID:'NEW',AccessModel:'FREE',Active:true});
view=await service.read('get');assert(view.needsSync);await save({mode:'matrix-prepare',operationId:crypto.randomUUID()});assert.equal(f.tables.AcademyAccessMatrix[1]['SUBJECT:NEW'],'USER');assert.equal(f.tables.AcademyAccessMatrix[1]['PROGRAM:REBOOT'],'TEACHER|ADMIN');
const newId=crypto.randomUUID(),create=await profile(newId);f.failNext('after');await assert.rejects(save(create),/Injected/);
const loginId=f.tables.UserAccounts.find(r=>r.AccountID===newId).UniqueID;
const replay=await save(create);assert(replay.replayed);assert.equal(replay.loginPath,`/account/${loginId}`);
assert.equal(f.tables.UserAccounts.filter(r=>r.AccountID===newId).length,1);assert.equal(f.tables.AcademyAccessMatrix.filter(r=>r.AccountID===newId).length,1);
const pending=await request('PERSON','SUBJECT','FREE',['SENIOR']);f.failNext('before');await assert.rejects(save(pending),/Injected/);
f.setAuthorized(false);await assert.rejects(coordinator.run('recover',{},'token'),/revoked/);f.setAuthorized(true);
assert((await coordinator.run('recover',{},'token')).recovered);assert((await save(pending)).replayed);
assert(f.tables.PlatformAuditLog.every(a=>a.AccountID==='OWNER'&&a.Authority==='GLOBAL_ADMIN'));
assert(!JSON.stringify(f.tables.AcademyProfileOperations).includes('private'));
console.log('Academy matrix: reviewed import, isolated legacy access, Free/Paid scope policy, combined roles, stable identities, incremental sync, conflicts, audit and authorized recovery passed.');
