import assert from 'node:assert/strict';
import { userProfilesFixture } from '../../scripts/user-profiles-fixtures.mjs';
import { profileService } from '../src/profiles/service.js';
import { timetableCoordinator } from '../src/programs/timetable-coordination.js';
const f=userProfilesFixture(),service=profileService(f.repository),coordinator=timetableCoordinator(f.journal,async()=>({service,user:f.authorize()}));
let view=await service.read('get');
const request=async(accountId,scopeType,scopeId,roles,extra={})=>{view=await service.read('get');const record=view.accounts.find(a=>a.accountId===accountId)?.assignments.find(a=>a.scopeType===scopeType&&a.scopeId===scopeId);return {operationId:crypto.randomUUID(),mode:'roles',accountId,scopeType,scopeId,roles,baseRevision:record?.revision,...extra};};
const save=input=>coordinator.run('save',input,'token');
const profile=async(accountId,extra={})=>{view=await service.read('get');const current=view.accounts.find(a=>a.accountId===accountId);return {operationId:crypto.randomUUID(),mode:'profile',accountId,creating:!current,displayName:current?.displayName||'New person',active:true,baseRevision:current?.revision||view.emptyRevision,...extra};};
assert.equal(view.accounts.length,2);assert(!JSON.stringify(view).includes('private'));assert(!JSON.stringify(view).includes('UniqueID'));
const rawAccount=structuredClone(f.tables.UserAccounts[1]);
await save(await profile('PERSON',{displayName:'Updated profile',PlatformRole:'GLOBAL_ADMIN',PINHash:'replace-me'}));
for(const field of ['UniqueID','PINSetup','PINHash','PlatformRole'])assert.equal(f.tables.UserAccounts[1][field],rawAccount[field]);
await assert.rejects(save(await profile('OWNER',{active:false})),/own account/);
const stale=await profile('PERSON');await save(await profile('PERSON',{displayName:'Another administrator edit'}));
await assert.rejects(save(stale),e=>e.code==='ROW_CHANGED'&&!JSON.stringify(e.currentRecord).includes('private'));
await assert.rejects(save(await request('PERSON','PROGRAM','PRG-DEMO',['STUDENT'])),/Confirm the paid subscription/);
await save(await request('PERSON','PROGRAM','PRG-DEMO',['STUDENT','TEACHER'],{subscriptionConfirmed:true}));
assert.deepEqual((await service.read('get')).accounts.find(a=>a.accountId==='PERSON').assignments.find(a=>a.scopeId==='PRG-DEMO').roles,['STUDENT','TEACHER']);
assert.equal(f.tables.UserCourseAccess.find(r=>r.AccessID==='LEGACY').Active,true);
await assert.rejects(save(await request('PERSON','PROGRAM','PRG-DEMO',['GLOBAL_ADMIN'])),/valid roles/);
await assert.rejects(save(await request('PERSON','PROGRAM','MISSING',['TEACHER'])),/Choose a global subject/);
await assert.rejects(save(await request('PERSON','SUBJECT','FREE',['STUDENT'],{subscriptionConfirmed:true})),/subject is free/);
await save(await request('PERSON','SUBJECT','PAID',['TEACHER','ADMIN']));
assert.equal(f.tables.GlobalSubjectAccessMatrix[1]._subjectAccess.PAID,false,'Staff roles do not claim a paid subscription');
await save(await request('PERSON','SUBJECT','PAID',['TEACHER','ADMIN','STUDENT'],{subscriptionConfirmed:true}));
assert.equal(f.tables.GlobalSubjectAccessMatrix[1]._subjectAccess.PAID,true);assert.equal(f.tables.GlobalSubjectAccessMatrix[0]._subjectAccess.PAID,true);
await save(await request('PERSON','SUBJECT','PAID',['TEACHER','STUDENT']));
assert.equal(f.tables.AcademySubjectRoles.find(r=>r.Role==='ADMIN').Active,false,'Removed roles remain recorded as inactive');
assert.equal(f.tables.GlobalSubjectAccessMatrix[1]._subjectAccess.PAID,true,'Removing staff role preserves subscription');
const beforeInactive=structuredClone([f.tables.UserCourseAccess,f.tables.GlobalSubjectAccessMatrix,f.tables.AcademySubjectRoles]);
await save(await profile('PERSON',{active:false}));
assert.deepEqual([f.tables.UserCourseAccess,f.tables.GlobalSubjectAccessMatrix,f.tables.AcademySubjectRoles],beforeInactive);
await assert.rejects(save(await request('PERSON','PROGRAM','PRG-DEMO',['STUDENT','TEACHER','ADMIN'])),/Reactivate the user/);
await save(await profile('PERSON',{active:true}));
await assert.rejects(save(await request('PERSON','PROGRAM','REBOOT',['TEACHER','ADMIN'])),/existing linked record/);
await save(await request('PERSON','PROGRAM','REBOOT',[]));assert.equal(f.tables.UserCourseAccess.find(r=>r.AccessID==='LEGACY').Active,false);
await save(await request('PERSON','PROGRAM','REBOOT',['TEACHER']));assert.equal(f.tables.UserCourseAccess.find(r=>r.AccessID==='LEGACY').CourseRecordID,'ADMIN-REAL');
// Lost responses and backend restart preserve the exact new identity and prevent duplicate subscriptions.
const newId=crypto.randomUUID(),create=await profile(newId);f.failNext('after');await assert.rejects(save(create),/Injected/);
const loginId=f.tables.UserAccounts.find(r=>r.AccountID===newId).UniqueID;
const replay=await save(create);assert(replay.replayed);assert.equal(replay.loginPath,`/account/${loginId}`);
assert.equal(f.tables.UserAccounts.filter(r=>r.AccountID===newId).length,1);assert.equal(f.tables.GlobalSubjectAccessMatrix.filter(r=>r.AccountID===newId).length,1);
const pending=await request('PERSON','SUBJECT','FREE',['SENIOR']);f.failNext('before');await assert.rejects(save(pending),/Injected/);
f.setAuthorized(false);await assert.rejects(coordinator.run('recover',{},'token'),/revoked/);f.setAuthorized(true);
assert((await coordinator.run('recover',{},'token')).recovered);assert((await save(pending)).replayed);
assert(f.tables.PlatformAuditLog.every(a=>a.AccountID==='OWNER'&&a.Authority==='GLOBAL_ADMIN'));
assert(f.tables.PlatformAuditLog.some(a=>a.ChangedFields.includes('paidSubscriptionConfirmed')));
assert(!JSON.stringify(f.tables.AcademyProfileOperations).includes('private'));
console.log('Shared profiles: stable identities, protected credentials, inactive preservation, scoped multi-role/subscription changes, conflict checks, legacy links, audit and authorized recovery passed.');
